# https://github.com/DavidAnson/markdownlint/blob/v0.37.2/README.md
# default to true for all rules
default: true
customRules:
  - "./styles/config/custom-quarto-rules.js"
  - "./styles/config/additional-quarto-rules.js"
  - "./styles/config/quarto-image-rules.js"
# Disable rules that conflict with Quarto syntax
MD033: false # Allow inline HTML
MD041: false # Allow content before first heading (for YAML frontmatter)
MD013: false # Disable line length restrictions
MD045: false # Disable standard image alt text rule, prefer our custom Quarto version
# Configure rules for better Quarto compatibility
MD007: # Unordered list indentation
  indent: 4
MD010: # No hard tabs
  code_blocks: false # Allow tabs in code blocks
MD022: # Headers should be surrounded by blank lines
  lines_above: 1
  lines_below: 1
MD024:
  siblings_only: true # Allow when nested under different parents e.g. CHANGELOG.md
MD025: # Single title/h1 header
  front_matter_title: "^title:" # Exclude YAML front matter title
MD031: # Blank lines around fenced code blocks
  list_items: false # Allow code blocks without blank lines in lists
MD038: false
MD040: # Fenced code blocks should have a language specified
  allowed_languages:
    - bash
    - r
    - python
    - yaml
    - json
    - html
    - css
    - javascript
    - markdown
    - sql
    - text
    - mermaid
    - dot
    - graphviz
    - stata
MD046: # Code block style
  style: fenced # Use fenced code blocks (```) rather than indented
MD047: false # new line at the end of file
MD048: # Code fence style
  style: backtick # Use backticks for code fences
# Options for Quarto-specific content
quarto-callout-blocks: true
quarto-callout-title: true
quarto-collapsible-callout: true
quarto-callout-appearance: true
quarto-callout-crossref: true
quarto-div-span: true
quarto-code-block: true
quarto-diagram: true
quarto-cross-reference: true
quarto-footnote: true
quarto-image-alt-text: true
