repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
        exclude: ^\.devcontainer/devcontainer\.json$
      - id: check-toml
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
  - repo: https://github.com/crate-ci/typos
    rev: v1.28.4
    hooks:
      - id: typos
        type_or: [markdown, quarto, python, pyi, jupyter]
        exclude: (.devcontainer|.quarto|.venv|.vscode|_site|_freeze|\.lock$)
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [--toml, pyproject.toml, --ignore-words=.codespell-ignore.txt]
        exclude: (.devcontainer|.quarto|.venv|.vscode|_site|_freeze|\.lock$)
        additional_dependencies:
          - tomli
  - repo: https://github.com/google/yamlfmt
    rev: v0.10.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint-fix
        type: [markdown, quarto]
        exclude: (.github/pull_request_template.md)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff-format
        types_or: [python, pyi, jupyter]
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi, jupyter]
        require_serial: true
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
    hooks:
      - id: actionlint
