project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "*.md"
    - "!page-template.qmd"
    - "!CONTRIBUTING.md"
    - "!LICENSE.md"
    - "!CLAUDE.md"
    - "!AGENTS.md"
    - "!docs/"
    - "!extensions/"
website:
  title: "Research and Data Science Hub"
  favicon: "assets/logos/ipa-favicon.ico"
  cookie-consent:
    type: implied
    style: simple
  google-analytics:
    tracking-id: "G-5YYP29ZV82"
    storage: cookies
    anonymize-ip: true
  bread-crumbs: true
  # announcement:

  #   icon: none
  #   dismissable: false
  #   content: "<span>📣 The IPA Research and Data Science Hub is under development [contact us with any feedback](mailto:researchsupport@poverty-action.org) or consider [contributing to the Hub](https://data.poverty-action.org/CONTRIBUTING.html)!</span>"
  #   type: light
  #   position: above-navbar
  back-to-top-navigation: true
  page-footer:
    background: light
  search:
    show-item-context: true
    location: navbar
    type: textbox
    limit: 20
  repo-url: https://github.com/PovertyAction/ipa-research-data-science-hub
  repo-actions: [edit, issue]
  page-navigation: true
  navbar:
    title: false
    background: white
    logo-alt: "IPA logo."
    collapse: true
    collapse-below: lg
    toggle-position: left
    tools-collapse: true
    pinned: false
    border: false
    # tools:

    #   - icon: github
    #     href: https://github.com/PovertyAction
    #     text: IPA GitHub
    right:
      - text: "Topics"
        menu:
          - text: "Research Design"
            href: ./research-design/index.qmd
          - text: "MEL"
            href: ./monitoring-evaluation-learning/ab-testing/index.qmd
          - text: "Research Ethics"
            href: ./research-ethics/index.qmd
          - text: "Data Quality"
            href: ./data-quality/index.qmd
          - text: "Data Security"
            href: ./data-security/index.qmd
          - text: "Data Collection"
            href: ./data-collection/index.qmd
          - text: "Data Cleaning"
            href: ./data-cleaning/index.qmd
          - text: "Data Science"
            href: ./data-science/index.qmd
          - text: "Research Transparency"
            href: ./research-transparency/understanding-transparency.qmd
      - text: "How-to Guides"
        menu:
          - text: "Data Security"
            href: ./data-security/how-to-data-security.qmd
          - text: "Stata DMS"
            href: ./data-quality/how-to-dms-stata.qmd
          - text: "Randomization"
            href: ./research-design/how-to-randomization.qmd
          - text: "Power Calculations"
            href: ./research-design/how-to-power-calculation.qmd
          - text: "Publish to Dataverse"
            href: ./research-transparency/how-to-publish-dataverse.qmd
      - text: "Software Guides"
        menu:
          - text: "The Shell"
            href: ./software/shell/index.qmd
          - text: "Git"
            href: ./software/git/index.qmd
          - text: "GitHub"
            href: ./software/github/index.qmd
          - text: "VS Code"
            href: ./software/vscode/index.qmd
          - text: "Stata"
            href: ./software/stata/index.qmd
          - text: "Python"
            href: ./software/python/index.qmd
          - text: "Quarto"
            href: ./software/quarto/index.qmd
      - text: "Contributing"
        href: ./CONTRIBUTING.qmd
  sidebar:
    style: floating
    collapse-level: 1
    align: left
    contents:
      - section: "Research Design"
        contents:
          - text: "About Research Design"
            href: ./research-design/index.qmd
          - text: "Research Methods"
            href: ./research-design/research-methods.qmd
          - text: "Randomization"
            href: ./research-design/randomization.qmd
          - text: "Sample and Power Calculations"
            href: ./research-design/sample-size-power.qmd
          - text: "Measurement"
            href: ./research-design/measurement.qmd
          - text: "Survey Translation"
            href: ./research-design/survey-translation.qmd
          - text: "Addressing Common Criticisms of RCTs"
            href: ./research-design/addressing-rct-criticisms.qmd
      - section: "Monitoring, Evaluation, and Learning (MEL)"
        contents:
          - text: "Theory of Change"
            href: ./monitoring-evaluation-learning/theory-of-change.qmd
          - section: "A/B Testing"
            contents:
              - text: "About A/B Testing"
                href: ./monitoring-evaluation-learning/ab-testing/index.qmd
              - text: "When A/B Testing Works"
                href: ./monitoring-evaluation-learning/ab-testing/when-ab-tests-works.qmd
              - text: "Implementing A/B Testing"
                href: ./monitoring-evaluation-learning/ab-testing/implementing-ab-tests.qmd
              - text: "Practical Guidance A/B Testing"
                href: ./monitoring-evaluation-learning/ab-testing/practical-guidance-ab-testing.qmd
      - section: "Research Ethics"
        contents:
          - text: "About IPA IRB"
            href: ./research-ethics/index.qmd
          - text: "IRB review"
            href: ./research-ethics/irb-review.qmd
          - text: "The IRB Lifecycle"
            href: ./research-ethics/irb-lifecycle.qmd
          - text: "Key Topics"
            href: ./research-ethics/irb-key-topics.qmd
          - text: "Reliance Agreements"
            href: ./research-ethics/irb-reliance-agreements.qmd
      - section: "Data Quality"
        contents:
          - text: "About Data Quality"
            href: ./data-quality/index.qmd
          - section: "IPA Research Protocols"
            contents:
              - text: "Survey Planning"
                href: ./data-quality/survey-plan.qmd
              - text: "Data Quality Action Plan"
                href: ./data-quality/action-plan.qmd
              - text: "Bench Testing"
                href: ./data-quality/bench-testing.qmd
              - text: "Pilot Survey"
                href: ./data-quality/pilot-survey.qmd
              - text: "Accompany Surveyors"
                href: ./data-quality/accompany-surveyors.qmd
              - text: "High-Frequency Checks"
                href: ./data-quality/high-frequency-checks.qmd
              - text: "Backchecks"
                href: ./data-quality/backchecks.qmd
              - text: "Data Anonymization"
                href: ./data-quality/data-anonymization.qmd
              - text: "AEA Registry"
                href: ./data-quality/aea-registry.qmd
              - text: "Data Integrity"
                href: ./data-quality/data-integrity.qmd
          - text: "IPA's Data Management System"
            href: ./data-quality/data-management-system.qmd
          - section: "DataSure"
            contents:
              - text: "About DataSure"
                href: ./data-quality/datasure/index.qmd
              - text: "How to Use DataSure"
                href: ./data-quality/datasure/how-to-datasure.qmd
      - section: "Data Security"
        contents:
          - text: "About Data Security"
            href: ./data-security/index.qmd
          - text: "Data Security Protocol"
            href: ./data-security/data-security-protocol.qmd
      - section: "Data Collection"
        contents:
          - text: "About Data Collection"
            href: ./data-collection/index.qmd
          - text: "In-Person Surveys"
            href: ./data-collection/in-person-surveys.qmd
          - text: "Phone Surveys"
            href: ./data-collection/phone-surveys.qmd
          - section: "WhatsApp Surveys"
            contents:
              - text: "About WhatsApp Surveys"
                href: ./data-collection/whatsapp/index.qmd
              - text: "Twilio Setup"
                href: ./data-collection/whatsapp/whatsapp-surveys-twilio.qmd
              - text: "Designing a WhatsApp Survey"
                href: ./data-collection/whatsapp/whatsapp-design.qmd
              - text: "Deploying a WhatsApp Survey"
                href: ./data-collection/whatsapp/whatsapp-deploy.qmd
              - text: "WhatsApp and Data Security"
                href: ./data-collection/whatsapp/whatsapp-data-security.qmd
          - section: "Qualitative Methods"
            contents:
              - text: "About Qualitative Methods"
                href: ./data-collection/qualitative-methods/index.qmd
              - text: "Focus Groups"
                href: ./data-collection/qualitative-methods/focus-groups.qmd
              - text: "Interviews"
                href: ./data-collection/qualitative-methods/interviews.qmd
              - text: "Rapid Ethnographic Assessments"
                href: ./data-collection/qualitative-methods/ethnographies.qmd
              - text: "Observations"
                href: ./data-collection/qualitative-methods/observations.qmd
              - text: "AI-Assisted Qualitative Coding"
                href: ./data-collection/qualitative-methods/ai-assisted-coding.qmd
          - text: "Administrative Data"
            href: ./data-collection/admin-data.qmd
          - section: "Fieldwork Management"
            contents:
              - text: "Field Staff Training"
                href: ./data-collection/fieldwork-management/field-staff-training.qmd
              - section: "Survey and Respondent Tracking"
                contents:
                  - text: "Why Tracking Matters"
                    href: ./data-collection/fieldwork-management/tracking/why-tracking.qmd
                  - text: "Survey Tracking"
                    href: ./data-collection/fieldwork-management/tracking/survey-tracking.qmd
                  - text: "Respondent Tracking"
                    href: ./data-collection/fieldwork-management/tracking/respondent-tracking.qmd
                  - text: "Longitudinal Tracking Strategies"
                    href: ./data-collection/fieldwork-management/tracking/longitudinal-tracking.qmd
                  - text: "Replacement Procedures"
                    href: ./data-collection/fieldwork-management/tracking/replacements.qmd
                  - text: "Mop-Up Operations"
                    href: ./data-collection/fieldwork-management/tracking/mop-up.qmd
      - section: "Data Cleaning"
        contents:
          - text: "About Data Cleaning"
            href: ./data-cleaning/index.qmd
          - text: "Raw Data Management"
            href: ./data-cleaning/raw-data-management.qmd
          - text: "Variable Management"
            href: ./data-cleaning/variable-management.qmd
          - text: "Dataset Documentation"
            href: ./data-cleaning/dataset-documentation.qmd
          - text: "Data Aggregation"
            href: ./data-cleaning/data-aggregation.qmd
      - section: "Data Science"
        contents:
          - text: "About Data Science"
            href: ./data-science/index.qmd
          - section: "Python Data Analysis"
            contents:
              - text: "Introduction to Python"
                href: ./data-science/data-analysis/index.qmd
              - text: "Running and Quitting"
                href: ./data-science/data-analysis/run-quit.qmd
              - text: "Variables and Assignment"
                href: ./data-science/data-analysis/variables.qmd
              - text: "Data Types and Conversion"
                href: ./data-science/data-analysis/types-conversion.qmd
              - text: "Built-in Functions"
                href: ./data-science/data-analysis/built-in.qmd
              - text: "Libraries"
                href: ./data-science/data-analysis/libraries.qmd
              - text: "Lists"
                href: ./data-science/data-analysis/lists.qmd
              - text: "For Loops"
                href: ./data-science/data-analysis/for-loops.qmd
              - text: "Conditionals"
                href: ./data-science/data-analysis/conditionals.qmd
              - text: "Looping Over Data Sets"
                href: ./data-science/data-analysis/looping-data-sets.qmd
              - text: "Writing Functions"
                href: ./data-science/data-analysis/writing-functions.qmd
              - text: "Variable Scope"
                href: ./data-science/data-analysis/scope.qmd
              - text: "Programming Style"
                href: ./data-science/data-analysis/style.qmd
              - text: "Reading Tabular Data"
                href: ./data-science/data-analysis/reading-tabular.qmd
              - text: "Pandas DataFrames"
                href: ./data-science/data-analysis/data-frames.qmd
              - text: "Plotting"
                href: ./data-science/data-analysis/plotting.qmd
          - section: "Web Scraping"
            contents:
              - text: "Introduction to Web Scraping"
                href: ./data-science/webscraping/index.qmd
              - text: "Getting Started with Gazpacho"
                href: ./data-science/webscraping/gazpacho-basics.qmd
              - text: "Making HTTP Requests"
                href: ./data-science/webscraping/getting-data.qmd
              - text: "Parsing HTML with Soup"
                href: ./data-science/webscraping/parsing-soup.qmd
              - text: "Integration with Pandas"
                href: ./data-science/webscraping/pandas-integration.qmd
              - text: "Advanced Selection"
                href: ./data-science/webscraping/strict-attributes.qmd
          - section: "Data Visualization"
            contents:
              - text: "Introduction to Visualization"
                href: ./data-science/data-visualization/index.qmd
              - text: "Introduction to Seaborn"
                href: ./data-science/data-visualization/intro-seaborn-objects.qmd
              - text: "Grammar of Graphics"
                href: ./data-science/data-visualization/grammar-of-graphics.qmd
              - text: "Marks and Geometric Objects"
                href: ./data-science/data-visualization/marks-geometric-objects.qmd
              - text: "Faceting and Layering"
                href: ./data-science/data-visualization/faceting-layering.qmd
              - text: "Labels and Customization"
                href: ./data-science/data-visualization/labels-scales-customization.qmd
              - text: "Statistical Transformations"
                href: ./data-science/data-visualization/statistical-transformations.qmd
              - text: "Themes and Final Polish"
                href: ./data-science/data-visualization/themes-final-polish.qmd
      - section: "Research Transparency"
        contents:
          - text: "Understanding Research Transparency"
            href: ./research-transparency/understanding-transparency.qmd
          - text: "Data Publication Preparation"
            href: ./research-transparency/publication-preparation.qmd
          - text: "How to Publish to Dataverse"
            href: ./research-transparency/how-to-publish-dataverse.qmd
      - section: "Software Guides"
        contents:
          - text: "Software Overview"
            href: ./software/index.qmd
          - section: "The Shell"
            contents:
              - text: "Introducing the Shell"
                href: ./software/shell/index.qmd
              - text: "File Management"
                href: ./software/shell/filedir.qmd
              - text: "Working With Files"
                href: ./software/shell/create.qmd
              - text: "Pipes and Filters"
                href: ./software/shell/pipefilter.qmd
              - text: "Loops"
                href: ./software/shell/loops.qmd
              - text: "Scripts"
                href: ./software/shell/scripts.qmd
              - text: "Finding Things"
                href: ./software/shell/find.qmd
          - section: "Virtual Environments"
            contents:
              - text: "Virtual Environments Overview"
                href: ./software/virtualenv/index.qmd
              - text: "Python Virtual Environments"
                href: ./software/virtualenv/python-uv.qmd
              - text: "Docker"
                href: ./software/virtualenv/docker.qmd
          - section: "Version Control"
            contents:
              - text: "Git"
                href: ./software/git/index.qmd
              - text: "Getting Started with Git"
                href: ./software/git/getting-started.qmd
              - text: "Creating a Repository"
                href: ./software/git/create-repo.qmd
              - text: "Cloning a Repository"
                href: ./software/git/clone-repo.qmd
              - text: "Git Configuration"
                href: ./software/git/configuration.qmd
              - text: "Tracking Changes"
                href: ./software/git/track-changes.qmd
              - text: "Push and Pull Changes"
                href: ./software/git/push-changes.qmd
              - text: "Working with Branches"
                href: ./software/git/branches.qmd
              - text: "Creating Pull Requests"
                href: ./software/git/pull-request.qmd
              - text: "Handling Merge Conflicts"
                href: ./software/git/conflicts.qmd
              - text: "GitHub"
                href: ./software/github/index.qmd
          - section: "Code Environments"
            contents:
              - text: "VS Code"
                href: ./software/vscode/index.qmd
          - section: "Stata"
            contents:
              - text: "Getting Started with Stata"
                href: ./software/stata/index.qmd
              - text: "Coding in Stata"
                href: ./software/stata/coding-stata.qmd
              - text: "Data Processing in Stata"
                href: ./software/stata/data-processing-stata.qmd
          - section: "Python"
            contents:
              - text: "Getting Started with Python"
                href: ./software/python/index.qmd
              - text: "Coding in Python"
                href: ./software/python/coding-python.qmd
              - text: "Processing Data in Python"
                href: ./software/python/data-processing-python.qmd
          - section: "Quarto"
            contents:
              - text: "Getting started with Quarto"
                href: ./software/quarto/index.qmd
              - text: "Writing in Quarto"
                href: ./software/quarto/basics.qmd
      - section: "Teams"
        contents:
          - text: "Research and Data Science"
            href: ./teams/grds.qmd
          - text: "Right-Fit Evidence"
            href: ./teams/rfe.qmd
# bibliography: references.bib

brand:
  light: assets/design-styles/light-brand.yml
  dark: assets/design-styles/dark-brand.yml
highlight-style:
  light: arrow
  dark: dracula
filters:
  - git-dates
format:
  html:
    respect-user-color-scheme: true
    toc: true
    appendix-style: none # removes "Reuse" appendix section
    theme:
      light: [litera, brand, assets/design-styles/light-theme.scss]
      dark: [litera, brand, assets/design-styles/dark-theme.scss]
    code-copy: true
    code-overflow: wrap
    css:
      - ./assets/design-styles/styles.css
    toc-title: "In this resource"
    template-partials:
      - ./assets/design-styles/toc.html
      - ./assets/design-styles/title-block.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
#   ipa-handout-typst:

#     theme: brand
#     papersize: a4
#     toc: false
#     columns: 1
#     number-sections: false
format-links:
  - format: typst
    text: PDF
    icon: file-pdf
language:
  search-text-placeholder: Search Resources
metadata-files:
  - _metadata.yml
execute:
  freeze: true
