---
title: "Installing Git"
# Authors
# Authors are the main creators of the site's content, credited for their work and responsible for its core development, including writing and editing.
authors-ipa:
  - "[Niall Keleher](https://poverty-action.org/people/niall-keleher)"

# Contributors
# Contributors provide support, such as feedback or supplementary materials for the site. They can also be responsible for updating/maintaining the site.
# contributors:
#   - "[Contributor 1](https://poverty-action.org/people/contributor1_name)"
---

:::{.custom-summary-block}
Get set up with Git, a version control system that helps you track changes in your files and collaborate with others. This guide will walk you through the installation process for Git on Windows, MacOS, and Linux.
:::

:::{.callout-note collapse="true"}
## Recognition and Attribution
This page modifies content from the [Software Carpentry Version Control with Git lesson](https://swcarpentry.github.io/git-novice/),  [Jenna Jordan's Intro to Git & GitHub (Speedrun edition)](https://jennajordan.me/git-novice-speedrun/), the [Carpentries Incubator Version Control with Git lesson](https://carpentries-incubator.github.io/git-novice-branch-pr/), and the [Library Carpentry Introduction to Git lesson](https://librarycarpentry.github.io/lc-git/).
:::

:::{.callout-tip appearance="simple"}
## Objectives
* Version control helps track changes to files and projects
* Git and GitHub are not the same
* Git commands are written as `git verb options`
:::

## How to install Git?

You must have Git installed on your local computer. Typically, Mac and Linux computers come pre-installed with git, while Windows users must install [Git for Windows](https://gitforwindows.org). However, you should first verify that Git is installed on your computer.

You can verify git is installed by opening a command line application (e.g. Terminal) and typing:

```bash
$ git version
```

If you see an error message stating git is an unknown command, you will need to install git.

If you do not already have git installed, you can refer to [this GitHub guide](https://github.com/git-guides/install-git) on installing git for any OS. The following instructions are a summary of the steps you can take to install git from the command line on Windows, MacOS, and Linux.

::: {.panel-tabset group="OS"}

# Windows

```bash
winget install Git.Git
```

# MacOS

```bash
# Git comes pre-installed with most MacOS distributions.
git --version
```

# Linux

```bash
# Git comes pre-installed with most Linux distributions.
git --version
```

:::
