---
title: "Ethics and IPA IRB"

#------------------------------------------------------------------
# Authors
#------------------------------------------------------------------
# Authors are the main creators of the site's content, credited
# for their work and responsible for its core development,
# including writing and editing.
#------------------------------------------------------------------
authors-ipa:
  - "[Alexandra Krstić](https://poverty-action.org/people/alexandra-krstic)"
  - "[Daniela Carrillo](https://poverty-action.org/people/daniela-carrillo)"
#------------------------------------------------------------------
# Contributors
#------------------------------------------------------------------
# Contributors provide support, such as feedback or supplementary
# materials for the site. They can also be responsible for
# updating/maintaining the site.
#------------------------------------------------------------------
---

:::{.custom-summary-block}
IRBs exist to protect the rights, safety, and welfare of human subjects involved in research projects,
:::

:::{.callout-tip appearance="simple"}
## Key Takeaways
* An Institutional Review Board (IRB) is an administrative committee designated to provide ethical and regulatory oversight of research that involves human subjects.
* IPA IRB ensures ethical oversight of human subjects research, requiring approval from a U.S. and a local IRB before research begins.
* IRB coverage options include review by IPA IRB, an external IRB, or a reliance agreement.
:::


## What is an Institutional Review Board?

An Institutional Review Board (IRB) is a group designated by an institution (e.g., a university or non-profit) to provide ethical and regulatory oversight of research involving human subjects. An IRB reviews, monitors, and, if necessary, requires modifications to these type of studies. Made up of IRB staff and board members, its primary role is to ensure that appropriate measures are taken to protect participants' rights, safety and welfare.

IRBs operate based on **ethical principles** outlined in the Belmont Report—beneficence, respect for persons, and justice—and adhere to minimum standards set by **U.S. federal regulations**, including the Department of Health and Human Services Regulations [(45 CFR part 46)](https://www.hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46/index.html). For human subject research conducted internationally, additional local regulations and international standards apply.

### Human Subjects Research
According to 45 CFR part 46, **human subjects research** means:

- **Research**: Systematic investigation, including research development, testing and evaluation, designed to develop or contribute to generalizable knowledge.
- **Human subject**: Living individual about whom an investigator (whether a professional or student) conducting research (i) obtains information or biospecimens through intervention or interaction with the individual, and uses, studies, or analyzes the information or biospecimens; or (ii) obtains, uses, studies, analyzes, or generates identifiable private information or identifiable biospecimens.

**IRB approval is mandatory for human subjects research**. The IRB is responsible of determining whether a study constitutes human subjects research. The research team cannot make this determination independently and must seek IRB review when there is any uncertainty.

::: {.callout-important}
## Need help determining if your project involves Human Subjects Research?
For more informarion on whether your project constitutes human subjects research, please consult the [Office for Human Research Protections decision charts](https://www.hhs.gov/ohrp/regulations-and-policy/decision-charts/index.html#c1) or contact IPA IRB at humansubjects@poverty-action.org.
:::

## About the IPA IRB

In 2007, IPA established an IRB that would provide ethical oversight to international studies that were primarily randomized trials with vulnerable populations in low and middle income countries where IPA operates. This IRB is hosted by IPA and its administrative functions are handled by IPA staff, but it is independent of IPA staff, management, and researchers. The membership  of the IPA IRB is diverse in affiliations and is composed of members who are external to IPA. The IRB convenes on a monthly basis.

IRB approval is a fundamental part of IPA's research quality protocols. IPA requires that all projects IPA in which IPA is involved be reviewed by a U.S. or a similar IRB institution, as well as nationally recognized (or equal) IRB in the country where the research is taking place (if such an IRB exists) before the start of any human subjects activities. When deciding how to arrange **IRB coverage for an IPA project**, the options are the following:

::: {.numbered-list}
1. **IPA IRB:** IPA IRB conducts its own review of the project.
2. **Health Media Lab (HML) IRB:** HML IRB may review the project in place of IPA IRB. Only projects which are minimal risk, involve no particularly sensitive questions or vulnerable subjects, and are not federally funded should submit to HML IRB.
3. **Reliance agreement with other institution**: In some cases, IRB review may be required at another institution (e.g., the PI's university, or the institution funding the study).If you prefer that IPA IRB cedes oversight to this other institution's IRB, we will need to set up a “reliance agreement” formally documenting this arrangement.
:::

### Meeting Dates

The IRB at IPA convenes regularly to review non-minimal risk studies and other submissions requiring full board review. To ensure timely consideration, researchers must submit all required materials by the deadlines listed in @tbl-irb-dates below. Submissions received after the deadline will be reviewed at the next available meeting. IRB meetings take place from 3 PM to 4 PM EST on the scheduled dates. Please plan accordingly to avoid delays in your study's approval process.

| Meeting Date                  | Deadline for Submission of Materials  |
|-------------------------------|---------------------------------------|
| Thursday, March 27, 2025      | Friday, March 7, 2025, COB            |
| Thursday, April 24, 2025      | Friday, April 4, 2025, COB            |
| Thursday, May 29, 2025        | Friday, May 9, 2025, COB              |
| Thursday, June 26, 2025       | Friday, June 6, 2025, COB             |
| Thursday, July 31, 2025       | Friday, July 11, 2025, COB            |
| Thursday, August 28, 2025     | Friday, August 8, 2025, COB           |
| Thursday, September 25, 2025  | Friday, September 5, 2025, COB        |
| Thursday, October 30, 2025    | Friday, October 10, 2025, COB         |
| Thursday, November 20, 2025   | Friday, October 31, 2025, COB         |
| Thursday, December 18, 2025   | Friday, November 28, 2025, COB        |

: IPA IRB Meeting Dates {#tbl-irb-dates}


### IRB Fee Schedule

The IPA IRB charges fees for its reviews based on the following [fee schedule](https://poverty-action.org/sites/default/files/2025-01/IPA%20IRB%20Fee%20Schedule%20-%20Effective%20March%201%202025.pdf). For more info on these fees, please click [here](https://poverty-action.org/sites/default/files/2025-01/IPA%20IRB%20Fee%20Update%20-%20March%201%202025.pdf). These fees are determined by (i) staff time and training, including processing submissions, executing reliance agreements, advising projects and responding to questions, preparing templates and customized guidance on consent forms, and recruiting and working with Board members; (ii) Board member honoraria; (iii) annual CITI organizational subscription for human subjects training; and (iv) comparison research to identify fees charged by other IRBs completed in 2024.

IRB fees should be included in every research project's budget. We advise that you discuss IRB during the project development stage together with your donors, PIs, and implementing partners so that you have adequately budgeted for the appropriate IRB costs.
