---
title: "IRB Review Requirements"

#------------------------------------------------------------------
# Authors
#------------------------------------------------------------------
authors-ipa:
  - "[Alexandra Krstić](https://poverty-action.org/people/alexandra-krstic)"

#------------------------------------------------------------------
# Contributors
#------------------------------------------------------------------
contributors:
  - "[Daniela Carrillo](https://poverty-action.org/people/daniela-carrillo)"
---

:::{.custom-summary-block}
This page explains various levels and types of "exemptions" from IRB review requirements. 
:::

:::{.callout-tip appearance="simple"}
## Key Takeaways
* Your project may not require IRB review if it falls outside the definition of "human subjects research"
* Your pilot study may or may not require IRB review, depending on what the data will be used for and the risk level of the activities
* If your project is human subjects research, it requires initial IRB review. However, it may still qualify for exemption from some future IRB oversight requirements if it falls into one or more 'exempt categories'
:::

## Does my project need IRB review?

It can be challenging to determine whether (or at what point) a project must be submitted for IRB review. This page outlines the different circumstances in which a project may not require IRB review.

:::{.callout-note}
## Not sure?
Please contact IPA IRB (humansubjects@poverty-action.org) if you have any uncertainty about whether your project needs IRB review.
:::

## Is my project human subjects research?

IRB review is required only for projects considered "human subjects research."

In somewhat rare cases, IPA works on projects which fall outside of this category, either because:
- The project does not involve "human subjects" (as defined by federal regulations), or
- The project is not considered "research" (again, as defined by federal regulations).

### Does my project involve human subjects?

Federal regulations define a "[human subject](https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-A/part-46#p-46.102(e)(1))" as:

A living individual about whom an investigator (whether a professional or student) conducting research:
1. Obtains information or biospecimens through intervention or interaction with the individual, and uses, studies, or analyzes the information or biospecimens; or
2. Obtains, uses, studies, analyzes, or generates identifiable private information or identifiable biospecimens.

The "about whom" clause of this definition is important. This means that if you are collecting data from someone, but this data is not in any way "about" them, they may not count as a human subject. For example: if your project involves interviewing factory workers, and you will only ask them questions about operations at the factory (what time it opens, steps in the manufacturing process, etc.), these interviewees may not count as human subjects (so long as you do not collect PII or any other information "about" them).

This sometimes comes up in the context of projects which involve interviews with staff or other key players in a program which IPA is evaluating. These interviews may not count as human subjects research if the questions you will ask are aimed only at learning about the program, how it functions, etc.—not anything specific to that interviewee or their experience. (If your survey includes questions asking the interviewee for their opinion about something—e.g., what do you think about this part of the program?—this may count as human subjects research).

### Is my project research?

Federal regulations define "[research](https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-A/part-46#p-46.102(l))" as:

A systematic investigation, including research development, testing, and evaluation, designed to develop or contribute to generalizable knowledge.

The end of this definition—"designed to develop or contribute to generalizable knowledge"—is the part most often relevant for determining whether IPA projects are considered research.

"Generalizable knowledge" typically means that the information generated through the project is expected to expand the knowledge base of a scientific discipline or other scholarly field of study and yield one or both of the following:
- Results that are applicable to a larger population beyond the site of data collection or the specific subjects studied.
- Results that are intended to be used to develop, test, or support theories, principles, and statements of relationships, or to inform policy beyond the study.*

Some projects that IPA works on fall outside of this category because their purpose is "program evaluation only." This means that the project's purpose is only to evaluate a specific program, and the only stakeholders interested in results of the study are program administrators or other entities interested specifically in the development or efficacy of that program. The results of the project will not be used to support conclusions about these types of programs in general.

Projects which fit the above description may not be considered "research" and thus may not require IRB review.

*Explanation borrowed from [University of Washington Human Subjects Division](https://www.washington.edu/research/hsd/do-i-need-irb-review/is-your-project-considered-research/)

## Do my pilot activities need IRB review?

Sometimes. Read on!

The purpose of a pilot is typically to evaluate the feasibility of a study and help researchers refine data collection procedures, instruments, or research design. They are usually small in scale and exploratory in nature.

Pilot activities are typically aimed at preparing for future, core research activities (i.e., those which are expected to generate results which will answer the main research questions).

Pilot activities are thus not considered research if they are intended only for this purpose and will not contribute to generalizable knowledge (i.e., results of the pilot will not be used as research data).

Pilot studies therefore typically do not require IRB review, with one key exception.

:::{.callout-warning}
## Exception:
If the pilot itself may create notable risks for subjects, IPA IRB may wish to review these activities. If your pilot will involve particularly vulnerable subjects, particularly sensitive questions/data collection, or research methods which may create greater than minimal risks, please consult with IPA IRB (humansubject@poverty-action.org) before beginning fieldwork.
:::

If data collected through a pilot study will be used for generalization or publication purposes (solely or in combination with other data), IRB review is required before data collection begins. Pilot data collected without IRB approval may not later be repurposed as study data, and the IRB cannot provide retroactive review.*

*Explanation borrowed from [Georgia Southern University Research Integrity](https://ww2.georgiasouthern.edu/research/researchintegrity/irb-faq/do-i-need-irb-approval-for-my-pilot-study/)

## My project is human subjects research—now what?

If your project is human subjects research (it involves human subjects, and it is research—i.e., not a pilot), an initial application must be submitted for IRB review.

However, it is still possible that your project may qualify for exemption from some future IRB oversight requirements.

### Categories of exempt research

Federal regulations outline several [categories](https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-A/part-46/subpart-A/section-46.104) of research which are considered 'exempt.' (These [decision charts](https://www.hhs.gov/ohrp/regulations-and-policy/decision-charts-2018/index.html) provide more info.)

Whether your research project fits within one or more of these categories can be difficult to interpret, so this determination must be made by the IRB (i.e., you cannot decide that your project is exempt).

Projects eligible for exemption are those which are very low risk. Eliminating unnecessary risks is the best way to increase the likelihood that your project will be found exempt. For example: if you are conducting a study involving only one round of data collection, and it is not necessary to collect PII, opting not to collect any PII will make your study more fit for exemption.

If your study involves deception, prisoner subjects, or child subjects, there are some additional limits on whether your study can be determined exempt.

### What does exemption mean?

Let's say you've submitted an initial application for your project, and the IRB has determined it 'exempt.' What does this mean for your IRB obligations going forward?

A determination of exemption means that the study does not need ongoing IRB oversight so long as the research remains minimal risk and stays within the bounds of the exemption categories that the IRB determined apply to this study.

In plain language, this means that:
- You do not need to submit renewals (so long as the project stays exempt).
- You do not need to submit amendments, so long as the changes you are making do not change or undermine the study's eligibility for exemption.

:::{.callout-warning}
## Important:
Projects may begin as exempt but change substantively over time such that they no longer qualify for exemption. It is crucial that you submit to the IRB any changes which may impact the exemption status of the study.
:::

These may include (but are not limited to):
- **Adding procedures which do not fit within the original exemption categories**
 - For example: if your original plan only involved working with secondary data or educational testing, and you are now planning to survey other participants.
- **Changes or new procedures that could affect risks to participants**
 - Removal of the consent process, or use of deception or incomplete disclosure.
 -  Significant changes to the recruitment procedures.
 - Collection of new or additional identifiable information.
 - Adding sensitive questions to a survey or interview process** (e.g., questions regarding illegal activities; traumatic events such as childhood, sexual, or domestic abuse; suicide; or other probing questions that could reasonably place the subjects at risk of criminal or civil liability or be damaging to the subjects' financial standing, employability, educational advancement, or reputation).
 - Changes to the data storage plan which may affect confidentiality.
- **Adding new types of participants, especially vulnerable populations** (including but not limited to: children, individuals with cognitive impairments, prisoners)

If you have any uncertainty about whether a particular change necessitates an amendment submission for your exempt project, please contact the IPA IRB (humansubjects@poverty-action.org).

**Other types of IRB submissions are still required:**
- Unexpected events must still be submitted if the research receives any participant complaints or experiences any unanticipated problems that involve risks to participants or others.
- The study must be closed once human subjects activities have concluded.