---
title: "Reliance Agreements"

#------------------------------------------------------------------
# Authors
#------------------------------------------------------------------
# Authors are the main creators of the site's content, credited
# for their work and responsible for its core development,
# including writing and editing.
#------------------------------------------------------------------
authors-ipa:
  - "[Alexandra Krstić](https://poverty-action.org/people/alexandra-krstic)"
  - "[Daniela Carrillo](https://poverty-action.org/people/daniela-carrillo)"
#------------------------------------------------------------------
# Contributors
#------------------------------------------------------------------
# Contributors provide support, such as feedback or supplementary
# materials for the site. They can also be responsible for
# updating/maintaining the site.
#------------------------------------------------------------------
---

:::{.custom-summary-block}
This page outlines when reliance agreements are needed, how to start them, and associated costs.
:::

![PLACEHOLDER IMAGE TITLE (® [IMAGE OWNER])](/assets/images/_image-placeholder.png){width=100%}

:::{.callout-tip appearance="simple"}
## Key Takeaways
* Reliance agreements allow IPA IRB to either cede oversight to another IRB or have another IRB rely on IPA IRB's review, ensuring compliance and reducing redundant reviews.
* Researchers must either submit to IPA IRB or set up a reliance with an IRB that has a Federalwide Assurance (FWA).
* Human subjects activities cannot begin until the reliance agreement has been signed by both IRBs.
:::

## What is a Reliance Agreement?

A reliance agreement is a formal, written agreement between two (or more) IRBs which enables one institution engaged in research to rely on another institution's IRB review.

Many research studies involve collaboration between investigators from multiple institutions which each maintain their own IRB. The advantage of a reliance agreement is that, rather than having multiple IRBs conduct their own full review of a research project, a reliance allows for only one institution to conduct a full review. This streamlines the IRB process and reduces burdens on investigators. A reliance agreement documents, in writing, the responsibilities of both the relying and reviewing institutions regarding IRB review, reporting, and oversight.

## When is a Reliance Agreement Needed?

For every study IPA is engaged in, ***IPA IRB must do one of the following***:

- IPA IRB conducts its own review of the project
- IPA IRB sets up a “reliance agreement” to formally cede oversight of the project to another institution's IRB.

These are the only two options. If you do not wish to submit your project to IPA IRB, it will be necessary to set up a reliance agreement with another IRB.

::: {.callout-tip collapse="true"}
## What kinds of institutions can IPA enter reliance agreements with?
IPA IRB can only enter reliance agreements with institutions that have a Federalwide Assurance (FWA). An FWA is a document held by an institution which signals that the institution has made a formal commitment to follow US federal regulations for the protection of human subjects. Most US-based university IRBs have FWAs. It is rarer for a local IRB to have an FWA, but some do. You can check whether an institution has an FWA [here](https://ohrp.cit.nih.gov/search/fwasearch.aspx?styp=bsc)
:::

::: {.callout-tip collapse="true"}
## Can I have another IRB rely on IPA IRB instead?

Yes! You may wish for IPA IRB to review the project and to have another institution (e.g., the PI's university) rely on IPA IRB's review. In some cases, a donor, partner organization, or PI's university may even require that IPA IRB conducts its own review of the study. (As of 2024, J-PAL requires that IPA projects receiving J-PAL funding be reviewed by IPA IRB - or HML IRB.)
:::

::: {.callout-tip collapse="true"}
## What about local IRB?
IPA IRB also requires that all projects be reviewed by a local IRB in the country where research is taking place (if such an IRB exists) before human subjects activities begin.
:::

## Setting up a Reliance Agreement

As early as possible, get in touch with both IPA IRB (humansubjects@poverty-action.org) and the other IRB you would like us to set up a reliance with. Different IRBs may have different policies about whether they are willing to enter reliances and different processes for evaluating reliance requests.

::: {.callout-tip collapse="true"}
## If you would like IPA IRB to cede oversight to another IRB...

Ask the other IRB if they are willing to allow IPA IRB to rely on their review. Once the other IRB has approved the project, send an email to humansubjects@poverty-action.org with:

- A completed Reliance Agreement Assessment Worksheet ([link to download from IPA IRB webpage])
- The approval letter and all approved materials (protocol, consents, surveys, etc.) from the reviewing IRB.
:::

::: {.callout-tip collapse="true"}
## Why does IPA IRB have to review project materials if it is ceding oversight of the project?

In order to assess whether we are willing to cede review of any given project, an initial limited review of the project must be done. This is necessary as there are certain kinds of projects (e.g., those involving significant risks or very vulnerable populations) that IPA IRB may be less comfortable ceding to another IRB. We also must make sure that the other IRB to whom we are ceding will do the kind of thorough oversight IPA IRB expects and would do itself. Once a reliance is established, IPA IRB then cedes review/trusts that the other IRB will provide adequate oversight of the project from that point forward (potentially for years, depending on the length of the project) - so it is only initially that a team must go through “review” with IPA IRB.
:::

::: {.callout-tip collapse="true"}
## If you would like another IRB to rely on IPA's review...

Ask the other IRB if they are willing to rely on IPA IRB's review. Then, send an email to humansubjects@poverty-action.org with:

- A completed Reliance Agreement Assessment Worksheet ([link to download from IPA IRB webpage])
- If not done already, prepare and submit an IRB application for your project for IPA IRB review.
:::

If IPA IRB will cede oversight another IRB, there is a $500 fee. This can be either charged to a grant or invoiced. If another IRB will rely on IPA IRB's review, there is no fee for the reliance agreement. However, regular IPA IRB review fees apply (for your initial application and any subsequent amendments, renewals, etc.).
