---
title: "The IRB Project Lifecycle"

#------------------------------------------------------------------
# Authors
#------------------------------------------------------------------
# Authors are the main creators of the site's content, credited
# for their work and responsible for its core development, 
# including writing and editing.
#------------------------------------------------------------------
authors-ipa:
  - "[Alexandra Krstić](https://poverty-action.org/people/alexandra-krstic)"
  - "[Daniela Carrillo](https://poverty-action.org/people/daniela-carrillo)"
#------------------------------------------------------------------
# Contributors
#------------------------------------------------------------------
# Contributors provide support, such as feedback or supplementary
# materials for the site. They can also be responsible for
# updating/maintaining the site.
#------------------------------------------------------------------
---

:::{.custom-summary-block}

:::


:::{.callout-tip appearance="simple"}
## Key Takeaways
* IRB project oversight begins with initial approval before study implementation and continues through required amendments, periodic renewals, and reporting of unexpected events.
* Oversight ends only when all human subjects interactions and PII data analysis are complete, requiring a formal closure submission.
:::

## Initial Application 



The IRB project lifecycle starts with the [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_original_application_form_updated_2020) of the initial application. An initial application is submitted to formally apply for **IRB review and approval should be secured prior to implementation** of a new research study. In this process, the IRB determines the level (expedited or full board) and frequency of continuing review (1 or 3 years). 

The submission should include the following documents:

- [IPA IRB Initial Application Form](https://poverty-action.org/sites/default/files/IPA-IRB-Original-Application_March-2022-Updated.docx) (once approved, it becomes the study's protocol)
- Instruments (e.g, surveys, interview/focus group discussion guides, observation forms)
- Informed consent forms ([IPA IRB consent checklist and template](https://poverty-action.org/sites/default/files/2023-09/IPA-IRB-Consent-Form-Checklist-and-Template-Formatted.pdf) can be used to ensure all required and assessed elements are included)
- Human Subjects Certificates for all Principal Investigators (PIs) and research personnel. Human Subjects training certification must be renewed every 3 years to be considered valid for approval
- IRB approval from local IRBs and/or other institutions
- Data Sharing Agreements
- Any other suporting documents


## Amendments

Amendments are modifications to the previously approved study protocol or documents. These modifications should be **IRB-reviewed and approved prior to implementation** to ensure that the regulatory criteria for IRB approval are still met and that the risk/benefit ratio remains reasonable. Amendments must be submitted via [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_amendment_form_updated_2020) and should include the following documents:

- [IPA IRB Amendment Form](https://poverty-action.org/sites/default/files/02-IPA-IRB-Amendment-Form.docx)
- Updated protocol
- Updated instruments (if proposing changes)
- Updated informed consent forms (if proposing changes)
- Updated Human Subjects Certificates (if expired or proposing changes to PIs and/or research personnel)
- Any other supporting documents


## Renewals

Renewals allow the IRB to provide continuing oversight of a research study by reviewing its progress and determining whether it continues to meet the regulatory criteria for approval. The renewal frequency is determined in the initial application review, can be found in the approval letter and depends on risk level, funding and start date. The renewal frequency is every 3 years for studies that meet the following requirements:

- Minimal risk
- Not federally funded
- Don't include vulnerable populations
- Don't include sensitive questions
- Started after October 2022

**All other studies should be renewed annually.** Renewals must be submitted via [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_renewal_closure_form_updated_2020) and should include the following documents:

- [IPA IRB Renewal Form](https://poverty-action.org/sites/default/files/IPA-IRB-Renewal-Form-Revised-Aug-2022.docx)
- Updated protocol (if also proposing changes)
- Updated instruments (if also proposing changes)
- Updated informed consent forms (if also proposing changes)
- Updated Human Subjects Certificates (if expired or proposing changes to PIs and/or research personnel)
- Any other supporting documents

::: {.callout-warning}
## Avoid delays or other issues by following IRB dates
Renewals should be submitted well in advance of the expiration date to avoid lapses in IRB approval. If a study’s approval expires, all research activities involving human subjects (e.g., data collection, contact with subjects, analysis of personally identifiable data (PII)) must stop until renewal is granted. If the renewal includes modifications, these proposed changes should be **reviewed and approved prior to implementation**.
:::


## Unexpected Events

Unexpected events are events that are not listed as risks in the protocol and/or informed consent forms like deviations or adverse events that result in harm to subjects. They must be **reported to the IRB** via [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_renewal_closure_form_updated_2020) **within 5 days** and should include the following documents:

- [IPA IRB Unexpected Event Form](https://poverty-action.org/sites/default/files/03-IPA-IRB-Unexpected-Event-Form.docx)
- Updated protocol (if needed)
- Any other supporting documents

::: {.callout-important}
**Once submitted:**
The IRB may require a corrective action plan to address the problem and, depending on the findings, additional reporting (e.g., to donor) may be required.
:::

## Closure

A closure submission notifies the IRB the study is complete and ends the study team's obligation to provide updates, resulting in the end of the IRB oversight. Closures must be submitted via [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_renewal_closure_form_updated_2020) and should include the following documents:

- [IPA IRB Closure Form](https://poverty-action.org/sites/default/files/IPA-IRB-Closure-Form-Revised-Aug-2022.docx)
- Any other supporting documents

Studies can be closed when data collection or interaction with subjects is done **AND** data analysis with PII is done