---
title: "The IRB Lifecycle"

#------------------------------------------------------------------
# Authors
#------------------------------------------------------------------
# Authors are the main creators of the site's content, credited
# for their work and responsible for its core development,
# including writing and editing.
#------------------------------------------------------------------
authors-ipa:
  - "[Alexandra Krstić](https://poverty-action.org/people/alexandra-krstic)"
  - "[Daniela Carrillo](https://poverty-action.org/people/daniela-carrillo)"
#------------------------------------------------------------------
# Contributors
#------------------------------------------------------------------
# Contributors provide support, such as feedback or supplementary
# materials for the site. They can also be responsible for
# updating/maintaining the site.
#------------------------------------------------------------------
---

:::{.custom-summary-block}
The typical IRB lifecycle consists of multiple stages including the initial application, amendments, renewals, reporting unexpected events, and closure.
:::

:::{.callout-tip appearance="simple"}
## Key Takeaways
* IRB project oversight begins with initial approval before study implementation and continues through required amendments, periodic renewals, and reporting of unexpected events.
* Oversight ends only when all human subjects interactions and PII data analysis are complete, requiring a formal closure submission.
:::

## Initial Application
The IRB project lifecycle starts with the [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_original_application_form_updated_2020) of the initial application. An initial application is submitted to formally apply for **IRB review and approval should be secured prior to implementation** of a new research study. In this process, the IRB determines the level (expedited or full board) and frequency of continuing review (1 or 3 years).

The submission should include the following documents:

- [IPA IRB Initial Application Form](https://poverty-action.org/sites/default/files/IPA-IRB-Original-Application_March-2022-Updated.docx) (once approved, it becomes the study's protocol)
- Instruments (e.g, surveys, interview/focus group discussion guides, observation forms)
- Informed consent forms ([IPA IRB consent checklist and template](https://poverty-action.org/sites/default/files/2023-09/IPA-IRB-Consent-Form-Checklist-and-Template-Formatted.pdf) can be used to ensure all required and assessed elements are included)
- Human Subjects Certificates for all Principal Investigators (PIs) and research personnel. Human Subjects training certification must be renewed every 3 years to be considered valid for approval
- IRB approval from local IRBs and/or other institutions
- Data Sharing Agreements
- Any other supporting documents

IPA IRB evaluates submissions on a rolling basis in the order that they are received. Upon receipt of an IRB submission for review, the research study is evaluated to determine whether it involves no more than minimal risk to the subjects. Minimal risk means that the probability and magnitude of harm or discomfort anticipated in the research are not greater than those ordinarily encountered in daily life or routine procedures. You can expect to receive feedback on your submission's risk assessment within 10 business days of your initial submission. Note that if the submission is incomplete or requires further clarification/modification, the approval timeline will depend on the nature of the necessary changes and the responsiveness of the responsible research staff.

**If your project is deemed to be minimal risk, it will undergo an expedited review**. Expedited review means the review is conducted by an IPA IRB representative designated by the IPA IRB Chair rather than necessitating a review by the full board. The reviews therefore are conducted on an ongoing basis. In other words, the research team does not need to wait for the next full board meeting for their submission to be reviewed or approved. Practically speaking, this means that the review usually does take less time than a non-minimal risk study. Expedited review can NOT be requested, because it is reflective of the study's risk level, which can only be determined by the designated representative of IPA IRB.

**If a project is non-minimal risk, the IRB Coordinator or the chair will refer a study to the full IRB Board**. The Board will review the study at the monthly meeting and then either propose changes or grant a decision. Thus, if you think your project may be non-minimal risk, the complete materials for the study must be received by the deadline associated with the corresponding targeted meeting date. If your submission is missing documents at the deadline, it may not be considered for that meeting date. Non-minimal risk applications that may need full board review should allow for 60 days to process, as the convened board may have questions or comments for the research staff that need to be re-discussed at the next meeting before they are able to issue an approval.

Please note that i​​​​f your pilot activity is collecting identifiable data that will be used for the duration of the study, you must budget enough time for your application to be approved prior to starting your pilot activities. 

## Amendments

Amendments are modifications to the previously approved study protocol or documents. These modifications should be **IRB-reviewed and approved prior to implementation** to ensure that the regulatory criteria for IRB approval are still met and that the risk/benefit ratio remains reasonable. Amendments must be submitted via [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_amendment_form_updated_2020) and should include the following documents:

- [IPA IRB Amendment Form](https://poverty-action.org/sites/default/files/02-IPA-IRB-Amendment-Form.docx)
- Updated protocol
- Updated instruments (if proposing changes)
- Updated informed consent forms (if proposing changes)
- Updated Human Subjects Certificates (if expired or proposing changes to PIs and/or research personnel)
- Any other supporting documents

Like application submissions, not all amendment submissions are reviewed by the full board at a convened meeting; only non-minimal risk submissions are. As long as your modification does not increase the risk of the research, it will be reviewed under expedited procedures. Regardless, you should submit your amendment as early as possible.

Note that if you are also due for a renewal, you can submit for changes and for the renewal (which extends the approval by one year or three years) with JUST the renewal form. More information on renewals can be found below.

## Renewals

Renewals allow the IRB to provide continuing oversight of a research study by reviewing its progress and determining whether it continues to meet the regulatory criteria for approval. The renewal frequency is determined in the initial application review, can be found in the approval letter and depends on risk level, funding and start date. **The renewal frequency is every three years for studies that meet the following requirements**:

- Are minimal risk
- Are not federally funded
- Don't include vulnerable populations
- Don't include sensitive questions
- Started after October 2022

**All other studies should be renewed annually.** 

Renewals must be submitted via [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_renewal_closure_form_updated_2020) and should include the following documents:

- [IPA IRB Renewal Form](https://poverty-action.org/sites/default/files/IPA-IRB-Renewal-Form-Revised-Aug-2022.docx)
- Updated protocol (if also proposing changes)
- Updated instruments (if also proposing changes)
- Updated informed consent forms (if also proposing changes)
- Updated Human Subjects Certificates (if expired or proposing changes to PIs and/or research personnel)
- Any other supporting documents

::: {.callout-warning}
## Avoid delays or other issues by following IRB dates
Renewals should be submitted well in advance of the expiration date to avoid lapses in IRB approval. If a study's approval expires, all research activities involving human subjects (e.g., data collection, contact with subjects, analysis of personally identifiable data (PII)) must stop until renewal is granted. In the progress report, you must also list the project's progress since last review, indicate why the deadline was missed, what human subjects research activities have taken place during the lapsed time, if any, and what steps will be taken by the PI to avoid missing deadlines in the future. Depending on the circumstances and length of delay in a continuing review, you may also be required to submit an unexpected event report, as this may represent serious or continuing non-compliance with reporting implications. If the renewal includes modifications, these proposed changes should be **reviewed and approved prior to implementation**.
:::

Note that renewal submissions are due each year or every three years, as applicable, at the time that the Initial Application was approved, not a year or three years after the most recent Amendment approval.

## Unexpected Events

Unexpected events are events that are not listed as risks in the protocol and/or informed consent forms like deviations or adverse events that result in harm to subjects. They must be **reported to the IRB** via [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_renewal_closure_form_updated_2020) **within 5 calendar days** and should include the following documents:

- [IPA IRB Unexpected Event Form](https://poverty-action.org/sites/default/files/03-IPA-IRB-Unexpected-Event-Form.docx)
- Updated protocol (if needed)
- Any other supporting documents

If you miss the deadline for reporting an unexpected event, it is still in the best interest of your project to report the event regardless of when it occurred. IPA is committed to protection of our human subjects and will work with all Country Programs to ensure appropriate protections occur and that appropriate responses are taken when an unexpected event happens.

::: {.callout-tip}
Once submitted, the IRB may require a corrective action plan to address the problem and, depending on the findings, additional reporting (e.g., to donor) may be required.
:::

## Closure

A closure submission notifies the IRB the study is complete and ends the study team's obligation to provide updates, resulting in the end of the IRB oversight. Closures must be submitted via [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_renewal_closure_form_updated_2020) and should include the following documents:

- [IPA IRB Closure Form](https://poverty-action.org/sites/default/files/IPA-IRB-Closure-Form-Revised-Aug-2022.docx)
- Any other supporting documents

Studies can be closed when data collection or interaction with subjects is done **AND** data analysis with PII is done.

Please note also that IPA IRB does not maintain a PII destruction policy and advises the following instead:
- Identified data may never be published in a public repository without respondent consent. Please verify that your data set does not contain any identifiers before publishing.
- Keeping identified information on file increases the risk of a confidentiality breach. IPA IRB encourages investigators to regularly weigh and re-assess this risk against the benefit of keeping this information, considering their project's unique circumstances and content.
- If the research team keeps identifiable information on file, they must keep this information confidential. IPA IRB assumes that the data security protections for the project PII will remain the same after the study's closure, unless they have been otherwise notified. IPA IRB retains the right to disallow alternative data security and confidentiality procedures for specific projects on a case-by-case basis.
- If the research team intends to contact subjects past the closure of the study for any reason, the original informed consent must have allowed for the possibility of re-contact for the express purpose proposed by the researchers. Re-contact must also be approved by the reviewing IRB for the closed study (and, if applicable, the IRB reviewing any new study) before it may be implemented.

