---
title: "Conducting Rapid Ethnographic Assessments"

#------------------------------------------------------------------
# Authors
#------------------------------------------------------------------
# Authors are the main creators of the site's content, credited
# for their work and responsible for its core development, 
# including writing and editing.
#------------------------------------------------------------------
authors-ipa:
  - "[Dahian Dimaté](https://poverty-action.org/people/dahian-dimate)"
  - "[Karen Moreno](https://poverty-action.org/people/karen-moreno-pinto)"
  - "[Maria Cecilia Dedios]()"
  - "[Nicól Lesmes](https://poverty-action.org/people/nicol-lesmes-guerrero)"
  - "[Nicolás Romero](https://poverty-action.org/people/nicolas-romero)"
#------------------------------------------------------------------
# Contributors
#------------------------------------------------------------------
# Contributors provide support, such as feedback or supplementary
# materials for the site. They can also be responsible for
# updating/maintaining the site.
#------------------------------------------------------------------
contributors:
  - "[Cristhian Pulido](https://poverty-action.org/people/cristhian-pulido)"
  - "[David Torres](https://poverty-action.org/people/david-francisco-torres-leon)"
  - "[German Acosta](https://poverty-action.org/people/german-acosta)"
  - "[Nicholas Guecha](https://poverty-action.org/people/nicholas-guecha)"
---

:::{.page-subtitle}
Rapid Ethnographic Assessments (REAs) are a complex method in qualitative research. In this article, the IPA Colombia team provides guidance on how to plan and implement REAs as part of your IPA projects.
:::


## 1. What are Rapid Ethnographic Assessments?

Rapid Ethnographic Assessment (REA) is a qualitative research method that allows the agile collection of information for decision-making. This methodology is characterized by several key features:

### Table 1: Properties of Rapid Ethnography

| Features                                      | Objective                                                                                                                                                                                                                                      |
|-----------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Conduct participant observations               | To approach the internal perspective of individuals in specific situations, from everyday life and the researcher's own experiences during events.                                                                                              |
| Use of field notes                             | To condense the preliminary results from various data collection techniques (e.g., focus groups, interviews, observations, etc.). These field notes include dense descriptions and reflective statements documenting the fieldwork, along with personal reflections. |
| Establish relationships with the community or participants | REA is based on the premise that extensive and in-depth information can be obtained through short, intensive, and participatory fieldwork with the community. This participatory aspect ensures active engagement and involvement. |
| Seek social and cultural relationships within a group of people | REA emphasizes understanding individual daily activities and group's culture, norms, activities, and social relations. In contrast to classic approaches, it offers a more specific focus, a shorter duration, and limited scope. |
| Holistic approach to the topics studied        | Conducting an REA allows the researcher to connect qualitative data collection techniques and other available data sources to rapidly generate insights. These insights are obtained through the researcher’s interpretations. The focus of REA is not objectivity but the identification of high-quality relationships among people, stories, and events mapped in the field. |

These principles have their roots in classical ethnography, which aims to understand a problem or situation from the "insider's" or "subject's perspective". Unlike classical ethnographies that involve extensive time (potentially months or years) in the field, Rapid Ethnographic Assessments (REA) are executed in a short period of time and seek to inform decision-makers in a timely manner. Some authors have suggested that REA should be conducted over four to six weeks.

With rapid ethnographies, information can be collected mainly through qualitative techniques, such as interviews, focus groups, and observations. However, quantitative techniques, such as available data and short surveys, can also be used to support the answer to the research questions.

To achieve relevant insights, REAs are characterized by the triangulation of results, the consolidation of multidisciplinary teams, and iterative learning processes. Combining multiple techniques positions rapid ethnography as a tool that provides findings and recommendations based on detailed, culturally relevant information reflecting local realities.

### 1.1 When is it useful to conduct a rapid ethnography?

REAs are particularly useful when practical and actionable recommendations are needed quickly. While this methodology has great potential, the rapid collection and processing mean that REA findings are exploratory. Their scope is limited to identifying findings from particular contexts rather than generating generalizable knowledge. In this sense, REA is especially useful when:

- More information is needed about an emerging problem or situation with little existing knowledge: Rapid ethnographies can provide descriptive information about poorly understood problems, helping to identify causes and design appropriate interventions.
- Engagement with “hidden” or vulnerable populations is necessary: Some populations may be particularly closed and difficult to reach. Accessing these groups requires the support of trusted individuals within the community. Rapid ethnographies often seek to identify and involve these community leaders to facilitate contact and build trust during the research.
- Community involvement is essential: Understanding how to address a problem requires the involvement of local community members. Involving the people who are directly affected by a problem often results in more practical and achievable recommendations for the program or intervention.

### Table 2: Examples of Uses of Rapid Ethnographies

| Examples of Uses of REA                                                                                                                                                                                                                                      |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Public Health:** After Hurricane Katrina, New Orleans experienced a demographic increase in the Latino population, particularly among single, undocumented men. Researchers suspected an emerging pattern of crack use among this population but needed more information to formulate responses. The REA results revealed how contextual factors such as a growing drug market, coupled with social isolation and victimization of the undocumented Latino population, led to the initiation and increase in crack use among a group that previously had relatively low drug use. |
| **Migration:** Accessing the migrant and refugee vulnerable population is a challenge due to factors such as stigmatization of the population due to lack of regular migratory status, lack of documentation, and distrust towards state institutions. Rapid ethnographies allowed for strategic approaches with community leaders and migrant organizations within local communities. Their involvement was fundamental in building trust in the community and accessing the target population, making them feel included and valued in the process. |
| **Emergency Contexts:** Between November 2020 and January 2021, during the COVID-19 pandemic, researchers conducted a REA in Dhaka, Bangladesh. They used in-depth interviews and participant observations to explore their health-related beliefs and practices. REA revealed a gap between scientific explanations of COVID-19 and the community's cultural and spiritual beliefs, such as the perception of the virus as a disease of the rich and sinners, leading many to reject biosecurity measures. These findings highlighted the need for a deeper understanding of community perceptions to improve the effectiveness of public health policies. |

## 2. What Kind of Information is Obtained?

The data produced during REA is gathered through a combination of various data collection techniques. The information and resources obtained from these techniques can be presented in a variety of formats. This interactive process involves the use of audio recordings from interviews and focus groups; photographs and videos taken during observation activities; texts resulting from note-taking during activities; and other resources such as maps or drawings that can be provided by the community. The mechanism of interaction between resources and the process on how that information contributes to generate insights depends on the scope of research questions and the strategy designed by the researcher to address rich information with time constraints.

### 2.1 How to Prepare?

Preparing for the conduct of a rapid ethnography involves i) identifying the methodological relevance to respond to the research objectives and questions; ii) carrying out logistical planning for the development of activities; iii) structuring the field team for the collection; and iv) designing a data reception plan that facilitates the triangulation of the information collected.

#### 2.1.1 Identify the Relevance of the Methodology and Design the Collection Instruments

- Validate that the selected methodology is appropriate to meet the research objectives. The first step is to identify whether rapid ethnography is the right approach to answer the research questions and objectives. A common question is how long does it take to conduct a rapid ethnography? Although there is no set rule on how much time is sufficient to conduct it, most experts agree that the time spent in the field collecting data should be between two and six weeks. The speed of data collection will depend on the research objectives, funding, and the technical expertise of the team. So ask yourself: When are the findings needed? Can the timeline be met? Are the necessary technical and financial resources available?
- Remember that a key aspect of rapid ethnographies is to produce actionable and timely data for decision-makers. If the timeline is not feasible and available funding is limited, another method may be more appropriate.
- Identify relevant ethical considerations. During planning, ensure that appropriate IRB permits and certifications are in place if required. This measure ensures that the research will not harm people and communities due to the project's processes or findings.
- Identify data collection techniques that will be prioritized. To prioritize, consider the information you want to collect and consult the practical guidelines for focus groups, interviews, and observations, as these are the most common collection techniques in REA. However, depending on the research needs and the research team's experience, other collection techniques such as ethnographic mapping or short surveys can be implemented. See in detail the data collection techniques used in rapid ethnographies; see Annex 1.

#### 2.1.2 Develop the Planning of Logistics Activities

- Contact allies, leaders, and key actors. Engage with local partners to understand contextual factors, convene participants, and coordinate logistics. Local partners can facilitate data collection.

**Considerations:**
- A field collection activity lasts, on average, 2 to 3 hours. Therefore, a maximum of two (2) activities per day is recommended. This ensures the quality of the data, does not exhaust the field team or the community, and avoids losing focus due to fatigue or saturation.
- In addition, the schedule of activities should include the time allocated by the team to i) travel or transport to the collection sites, ii) collect data, iii) take notes, and iv) refine the field notes and integrate other resources generated.

- Make a schedule defining the field collection activities. Define all field collection activities and the total number of tasks to be completed and the time available for this purpose. Share the schedule with allies and key stakeholders to:
  - Confirm participant availability on the selected dates.
  - Identify locations where activities will take place.
  - Ensure there are no conflicting events in the community.
  - Visual tools such as a Gantt chart are suggested for developing the schedule.

- Verify the location and conditions of the places where the collection activities will take place. Remember that it is essential to identify safe locations that facilitate interaction with the community. If possible, work with local community organizations and leaders. Before beginning fieldwork, gather general field information and visit the community with someone locally trusted to establish rapport and familiarize yourself with the area.
- Ensure the safety of the field team. Rapid ethnographies often take place in communities where there are high degrees of vulnerability and dynamics of violence and illegal activities, among others. Conduct a thorough risk assessment during the planning phase and prioritize the safety of both the field team and the community to minimize risks.
- Ensure that you have all the necessary materials to carry out the activities. This includes preparing incentives for participants (if applicable), refreshments, stationery, attendance lists, informed consents (if applicable), recording equipment, photographic equipment, batteries, etc.

#### 2.1.3 Structure Your Team

When structuring your team, carefully consider who will make up an effective and productive team. Take into account the experience required for each role and ensure that team members are well-suited to the tasks they will perform in the field. To that end:

- Define who will be in the field and the characteristics that each team member should have. The best multidisciplinary teams comprise people with complementary skills and technical or subject matter expertise. In addition, teamwork has been identified as beneficial, as it facilitates the development of ethnographic research from different points of view, often integrating knowledge from various fields, areas, or topics. Three essential elements of a strong OER team are: i) expertise in qualitative methods, ii) expertise in content or topics, and iii) expertise in the local context.
  - First, there should be at least one person on the project team with experience in qualitative research methods, who will be responsible for helping to keep the project on track by monitoring the quality of the data collected and training team members when necessary. This role will facilitate learning from participants due to their ethnographic orientation and sensitivity to the project.
  - Second, it is desirable to have people with thematic expertise and actively involve stakeholders. Thematic experts could guide the research team in understanding the findings nuances and connecting it with literature, as well as provide institutional context, depending on the study topic. In turn, stakeholders can act as advisors throughout the study, ensuring relevance and facilitating the incorporation of findings into practical changes.
  - Finally, the team should include people who are closely involved on a daily basis with the problem or phenomenon under study. These are usually people from the local community or target population. These people are sometimes called "cultural experts." They should be a trusted person who can help facilitate access and interaction with hard-to-reach populations and provide information on how things are organized within their community.

- Be aware of qualitative skills that the fieldwork team should have: The data quality produced during qualitative research activities is related to the research team's skills in collecting the information. The literature has identified specific competencies (cognitive empathy, monitoring, self-recognition, heterogeneity, and palpability) that enable fieldwork teams to understand in depth the perceptions, meanings, and motivations of the people they are studying and to recognize and adequately represent diversity within qualitative data.

The skills described in Table 3 are acquired, developed, and strengthened through years of study and practice in qualitative methodologies. However, field teams tend to be multidisciplinary in monitoring and evaluating social programs and have varying levels of experience. For now, there are no metrics to measure the prevalence of these skills in those who moderate qualitative fieldwork. Therefore, the skills in the following table should be understood as a resource for reference and reflection among the teams.

### Table 3: Desirable Skills in the Field Team

| Ability                     | Description                                                                                                                                                                                                 | Why is this skill important?                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|-----------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Cognitive empathy           | The field team's ability to understand and communicate participants’ situations from their perspectives, understanding how they see the world and their roles within it.                                    | Allows researchers to connect more deeply with participant's realities and experiences. Helps to create a relationship of trust and respect with the participants. Seeks to avoid generalizations and stereotypes that may arise from preconceptions or external influences such as previous studies. Enhances understanding of participants’ situations without resorting to pity.                                                                                   |
| Follow-up                   | The field team's ability to recognize when additional information is needed to answer the questions initially posed and those that arise during the research process. This ability implies curiosity and a willingness to explore new issues or doubts that emerge as data collection progresses. | Increases the quality and robustness of data by allowing a more detailed exploration of the studied phenomenon. Contributes to obtaining deeper responses from participants. Enables exploration of emerging themes during data collection. Helps detect and validate patterns observed in the field.                                                                                                             |
| Self-awareness and reflexivity | The field team's ability to continuously reflect on how their presence, background, and assumptions influence data collection, interpretation, and analysis. This ongoing self-reflection ensures that the qualitative field team is mindful of its impact on the research process and the participants. | Helps maintain ethics in the researcher-participant relationship. Facilitates understanding of personal limitations in connecting with participants. Aids in developing strategies to overcome communication barriers and create an environment where participants feel comfortable sharing sensitive information.                                                                                                 |
| Heterogeneity               | The field team's ability to represent and reflect the diversity within the group being studied. This skill involves recognizing and documenting the differences and variations among individuals or subgroups during qualitative research, typically applied during the data analysis phase. | Contributes to challenging generalized and simplistic patterns. Ensures that data reflect both common and atypical experiences. Demonstrates the field team's ability to identify, recognize, and document heterogeneity in the population studied.                                                                                                                         |
| Palpability                 | The field team's ability to provide detailed descriptions in their field notes or diaries, making the data tangible and clear. This involves avoiding abstract descriptions and, instead, offering vivid accounts that allow the research team to visualize and understand participants' experiences and contexts. | Reliable findings are supported by specific details that clearly depict the events and situations studied. Helps to avoid abstraction in the data, grounding conclusions in concrete evidence.                                                                                                                                                                                                                                                         |

- Assign roles and functions to each team member. Before starting the collection, define the roles and functions of the field team. Some key roles and functions must be assigned to achieve the proposed objectives. To do this, make a role assignment matrix to organize the tasks of contacting or scheduling participants, logistics of access to the territory, information collection, data flow closure, and analysis.

#### 2.1.4 Plan to Ensure Effective Fieldwork and Secure Storage of Gathered Information

In addition to logistical planning, the team must decide how to handle the collection and secure management of data to ensure its quality and facilitate its subsequent systematization. To this end:

- Define who will lead data collection and reception within the team. From the beginning, one person should lead the instrument design, data collection, resources reception (based on fieldwork results), and analysis. Ideally, this person should have experience applying qualitative research methods and be involved in fieldwork and data collection. This person's involvement in the project's different stages will make it easier to manage the information collected and ensure the integration of the various sources and resources.
- Define a note-taking strategy for the different activities. Note-taking is an essential activity across all data collection activities in REA, even if recordings are available.

For note-taking, the team leader should agree with the team on:

- Format that everyone will use for their note-taking
- Critical aspects that require more or less attention from the team to address in the notes
- Types of formats that could complement the notes (photographs, videos, maps, etc.)
- Dates for intermediate and final results

Having a common understanding of these processes will ensure the smooth flow of data collection and a clear scope of each role within the team.

- Study the instruments, scripts, and practical guides provided to ensure data quality during data collection. Before fieldwork, all team members should familiarize themselves with the characteristics of the instruments and the type of notes and supplementary resources to be generated in each case. Use the practical guides provided to prepare accordingly for the prioritized techniques.

## 3. What to Do During and After the Rapid Ethnography?

### 3.1 During Rapid Ethnography

In addition to gathering information through the prioritized data collection techniques, it is essential to allocate time for regular team meetings during fieldwork. The success of rapid ethnographic assessments (REA) often depends on team interaction and the triangulation of data sources, methods, and perspectives. To ensure this:

#### 3.1.1 Establish Periodic Check-In Meetings with the Team

During fieldwork, the team should meet periodically to share insights and determine if adjustments are needed for upcoming activities. These debriefing sessions are a key component of rapid ethnography and should be scheduled to ensure they are not overlooked.

**Considerations:**
- Due to time constraints, it's tempting to skip check-ins or leave discussions for after fieldwork is complete—this is a mistake!
- Sharing information in a group setting improves the quality of data collection and subsequent analysis. Make sure blocks of time are scheduled in advance for these meetings.
- Ideally, teams should have these sessions once every two days during fieldwork. These sessions help identify topics needing additional information and those that may have reached saturation where no new information is emerging.

**Guiding Questions for Check-Ins:**
- Were there any unexpected or stressful events?
- How well did you perform as an interviewer, moderator, observer, or note-taker?
- What kind of data did you collect?
- Are there any gaps that need follow-up?
- What adjustments would you make to the data collection guides or techniques?
- Are there new sites or contexts that need observation?

Take notes during these meetings to track follow-up actions. These sessions are also a chance to discuss the project’s progress, address logistical challenges, and provide team members with training or advice on collection techniques.

#### 3.1.2 Potential Challenges During Check-Up Meetings and Fieldwork Development

### Table 4: Challenges and Solutions During Check-Up Meetings and Fieldwork

| Challenges                                                                 | Possible Solutions                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|----------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| One team member usually dominates the conversation during debriefing meetings | Emphasize the importance of teamwork during training. Rotate facilitators for check-in meetings to give everyone a chance to lead and ensure balanced participation. Foster an environment where each team member shares their insights.                                                                                                                                                                                                                                                                                   |
| Field teams may encounter challenges in implementing reflexivity practices when conducting REAs | Encourage ongoing communication about biases that may influence data interpretation. Adapt meeting formats to fit fieldwork dynamics. Use flexible field diaries to document biases while accommodating the pace and nature of the research.                                                                                                                                                                                                                                                                               |
| There is an evident lack of consistency in collecting information among the field team | Implement standardized data collection tools and provide clear instructions on using them. During training, discuss the context of the REA and emphasize shared best practices for approaching unstructured situations.                                                                                                                                                                                                                                                                                                     |
| Some team members need to pay more attention to the ethical aspects of the research | Accelerated timelines can lead to ethical lapses. Emphasize the importance of ethical practices during training and ensure that all team members understand how to uphold ethical standards to protect participants and maintain data integrity.                                                                                                                                                                                                                                                                              |
| Team members say they are uncomfortable with the activities they witness    | Discuss potential uncomfortable situations during training so that team members are prepared. If discomfort arises in the field, reassign less sensitive tasks to the team member and ensure they can perform their role without bias. Some team members may be unsuitable for certain projects due to personal beliefs or values.                                                                                                                                                                                                                                   |
| Some team members are trained and oriented quantitatively and unfamiliar with REAs and qualitative methods | Provide thorough training on qualitative methods and the specific REA protocols. Ensure that all team members understand their roles in data collection, including note-taking and techniques. Rotate tasks to allow everyone to gain hands-on experience in different aspects of the REA process.                                                                                                                                                                                                                                                                |

### 3.2 After REA Collection Activities

#### 3.2.1 Perform Data Management and Preparation

**Use of Photographic Material:**
Photographs are excellent complements to field notes. While they don’t need to be technically perfect, their primary function is to document key details and provide contextual information. However, always follow ethical guidelines to ensure participants' safety and confidentiality before taking photographs.

Once data collection is complete, the team will have multiple sources of information, resources, and data from the research activities conducted in the field. To ensure proper management of these data, the following steps are suggested:

- First, after each data collection journey, each team member must ensure secure data collection storage according to the protocols for developing human subject research defined for the project.

**Follow these steps:**
- Transfer all recordings, photographs, and audiovisual material to the designated folders or storage platforms.
- Name files according to protocol.
- Anonymize and encrypt sensitive material to protect participants’ privacy.

**Remember:**
The lack of initial documentation products jeopardizes all the information processing components and, therefore, the data quality obtained.

- Second, field notes are the primary data source for rapid ethnographies, so it is crucial to write and expand them as soon as possible, ideally within 24 hours of collection. To do this, integrate complementary material and resources, such as photographs, videos, maps, drawings, field diaries, etc., into the field notes, according to the protocols and quality criteria agreed upon with the team in the planning phase. Standardizing this process will save time during the systematization phases, prevent data loss, and facilitate the project leader’s review of the information.

## 4. Considerations for Conducting Digital Ethnographies

The internet and digital technologies have accelerated the way people live, work, and relate to each other. In response to this social phenomenon, digital ethnography has emerged, a method that studies how people behave and interact in virtual environments, creating communities in digital spaces.

Digital ethnography adapts traditional ethnographic research techniques to studying online cultures and communities formed through communications mediated by a computer or mobile device. Instead of physically being in a community, researchers immerse themselves in online communities, forums, and social networking platforms. This way, the digital ethnographer observes and analyzes how individuals interact in these virtual spaces.

Techniques commonly used in digital ethnography are participant and non-participant observation, interviews, focus groups, and short surveys. To conduct a digital ethnography, follow the steps described above for performing a rapid ethnography. In addition, these considerations will be useful when adapting this method to a digital environment.

### Table 5: Considerations and Challenges in Digital Ethnographies

| Challenges                          | Description                                                                                                                                                                                                                                      | Possible Solutions and Recommendations                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|-------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Ethical concerns: Informed consent  | Obtaining informed consent from online participants can be challenging.                                                                                                                                                                           | Whenever possible, contact participants and share and socialize the informed consent. Some platforms may have specific terms of service, but it is essential to ensure that participants understand the research and agree to participate voluntarily.                                                                                                                                                                                                                                                                                       |
| Ethical concerns: Anonymity and privacy | Protecting the privacy and anonymity of participants in virtual environments is becoming more complex.                                                                                                                                             | Some platforms may have specific terms of service and data processing. Please review these terms. Researchers should inform participants if they intend to share information so that appropriate measures can be taken and the risk of participant identification minimized if the participant does not wish to be identified.                                                                                                                                                                                                                 |
| Digital divide: Disparities in access | Not everyone can access the Internet or digital devices equally.                                                                                                                                                                                  | Be mindful of access gaps that may lead to a biased sample, excluding certain demographic groups and limiting the generalizability of the findings.                                                                                                                                                                                                                                                                                                                                                                                           |
| Digital divide: Low digital literacy | Participants may have no or low skills in handling technological devices, which may affect their online behaviors.                                                                                                                                 | These differences should be considered when presenting findings during the data analysis and interpretation phases. When using WhatsApp, use the application's various resources, such as voice notes, images, videos, and stickers, to convey information accurately, directly, and responsively to users with these difficulties.                                                                                                                                                                                                                 |
| Data quality and authenticity: Incorrect representation | Participants may present themselves differently online, creating a potential gap between their online persona and offline identity.                                                                                                                | Note that automated accounts, trolls, and fake profiles can complicate data interpretation and introduce biased information into the analysis. Always be aware of the potential for misrepresentation in digital environments.                                                                                                                                                                                                                                                                                                                |
| Low participation: Interaction at problematic times | Participants may need help participating in the activities due to schedule conflicts or lack of time availability.                                                                                                                                 | Conduct baseline surveys to identify the schedules that best meet the population's needs. From the beginning, underline clear rules about desirable times to receive messages.                                                                                                                                                                                                                                                                                                                                                               |
| Low participation: Lack of trust     | Participants may be distrustful of being artificially linked to virtual communities.                                                                                                                                                               | Make prior contact with participants before linking them to virtual spaces to introduce them to the organization. Present again the purpose of the research. Sometimes, participants do not complete the informed consent form.                                                                                                                                                                                                                                                                                                               |
| Interpretation: Difficulty in interpreting content | Messages shared by participants may present an interpretive challenge for the researcher, as the tone of the message is attributed by the reader.                                                                                                  | Actively moderate to ask counter-questions to clarify the message. Promote clear communication in written messages. Record questions arising from participation in virtual scenarios from participant interactions in your field diary or field note.                                                                                                                                                                                                                                                                                        |



