{
  "hash": "4df73592dcd2a62cc979bd0c7cf69876",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Guide to Power Calculations\"\nabstract: \"Learn how to perform power calculations for randomized controlled trials using Stata's power command. This guide covers three essential scenarios: calculating required sample size, determining minimum detectable effect, and estimating statistical power for given parameters.\"\ndate: last-modified\n\n#------------------------------------------------------------------\n# Authors\n#------------------------------------------------------------------\n# Authors are the main creators of the site's content, credited\n# for their work and responsible for its core development,\n# including writing and editing.\n#------------------------------------------------------------------\nauthors-ipa:\n    - \"[Cristhian Pulido](https://poverty-action.org/people/cristhian-pulido)\"\n\n#------------------------------------------------------------------\n# Contributors\n#------------------------------------------------------------------\n# Contributors provide support, such as feedback or supplementary\n# materials for the site. They can also be responsible for\n# updating/maintaining the site.\n#------------------------------------------------------------------\ncontributors:\n  - \"[David Torres](https://poverty-action.org/people/david-francisco-torres-leon)\"\n\nkeywords:\n  - \"statistical power\"\n  - \"sample size calculation\"\n  - \"randomized controlled trials\"\n  - \"minimum detectable effect\"\n  - \"research design\"\n  - \"how-to guide\"\n\nlicense: \"CC BY\"\n---\n\n\n\n## When to Use Power Calculations\n\nPower calculations help researchers determine the feasibility and design parameters of their studies before data collection begins. Use power calculations to:\n\n- Plan adequate sample sizes for your research budget\n- Set realistic expectations for effect detection\n- Justify sample size decisions to funders and reviewers\n- Compare different study design options\n\nThis guide demonstrates three common power calculation scenarios using a hypothetical education intervention in India.\n\n## Practical Tools and Applications in Stata\n\n### Using the `power` Command in Stata\n\nThis guide uses Stata's `power` command to perform sample size and power calculations, and to create sensitivity tables and graphs.[^3]\n\n📌 **Type this in Stata for help:**\n\n```stata\nhelp power\n```\n\nThe India education intervention example illustrates three types of power analysis:\n\n::: {.callout-tip collapse=\"true\"}\n\n## 🧮 Case 1: Estimate Required Sample Size\n\n**Goal:** Determine how many participants you need to detect an expected effect.\n\n**Assumptions:**\n\n- Effect size or minimum detectable effect: 0.2 S.D.\n- Statistical power: 80%\n- Variance of the outcome variable: 1 S.D.\n- A single treatment group and a control group\n- A single post-treatment data collection at endline\n- Program randomization at the individual child level\n- Perfect compliance\n- No attrition\n- No additional controls\n\n**Stata code:**\n\n::: {#ed11bbe8 .cell execution_count=2}\n``` {.python .cell-code}\n%%stata\npower twomeans 0 0.2 , power(0.8) sd(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nPerforming iteration ...\n\nEstimated sample sizes for a two-sample means test\nt test assuming sd1 = sd2 = sd\nH0: m2 = m1  versus  Ha: m2 != m1\n\nStudy parameters:\n\n        alpha =    0.0500\n        power =    0.8000\n        delta =    0.2000\n           m1 =    0.0000\n           m2 =    0.2000\n           sd =    1.0000\n\nEstimated sample sizes:\n\n            N =       788\n  N per group =       394\n```\n:::\n:::\n\n\nThis tells Stata to calculate the required sample size for each group—treatment and control—to detect a 0.2 S.D. effect. The required study sample size to achieve a power of 80% is 788 students: 394 in the treatment group and 394 in the control group.\n\n**Stata code:**\n\nNow, suppose researchers expect a larger treatment effect of 0.4 standard deviations instead of 0.2 S.D., keeping all other assumptions the same. To calculate the required sample size for this new scenario:\n\n::: {#4dade7e3 .cell execution_count=3}\n``` {.python .cell-code}\n%%stata\npower twomeans 0 0.4 , power(0.8) sd(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nPerforming iteration ...\n\nEstimated sample sizes for a two-sample means test\nt test assuming sd1 = sd2 = sd\nH0: m2 = m1  versus  Ha: m2 != m1\n\nStudy parameters:\n\n        alpha =    0.0500\n        power =    0.8000\n        delta =    0.4000\n           m1 =    0.0000\n           m2 =    0.4000\n           sd =    1.0000\n\nEstimated sample sizes:\n\n            N =       200\n  N per group =       100\n```\n:::\n:::\n\n\n**Stata code:**\n\nNow, changing the assumption: **What if researchers want to increase the statistical power to 90%?**\n\nTo calculate the required sample size for an effect size of 0.4 S.D. and 90% power:\n\n::: {#e000e6d6 .cell execution_count=4}\n``` {.python .cell-code}\n%%stata\npower twomeans 0 0.2 , power(0.9) sd(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nPerforming iteration ...\n\nEstimated sample sizes for a two-sample means test\nt test assuming sd1 = sd2 = sd\nH0: m2 = m1  versus  Ha: m2 != m1\n\nStudy parameters:\n\n        alpha =    0.0500\n        power =    0.9000\n        delta =    0.2000\n           m1 =    0.0000\n           m2 =    0.2000\n           sd =    1.0000\n\nEstimated sample sizes:\n\n            N =     1,054\n  N per group =       527\n```\n:::\n:::\n\n\nThe required sample size would increase to 1,054.\n\nAdditional exercises are available in the following do file: [Download power.do](/assets/files/sample-size-power.do)\n:::\n\n::: {.callout-tip collapse=\"true\"}\n\n## 🧮 Case 2: Estimate Minimum Detectable Effect\n\n**Goal:**  Find the smallest effect size you can detect given your sample size.\n\n**Assumptions:**\n\n- Sample size: 1,000 students with 500 per group\n- Power: 80%\n- Variance of the outcome variable: 1 S.D\n\n**Stata code:**\n\n::: {#708ed70d .cell execution_count=5}\n``` {.python .cell-code}\n%%stata\npower twomeans 0 , n(1000) power(0.8) sd(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nPerforming iteration ...\n\nEstimated experimental-group mean for a two-sample means test\nt test assuming sd1 = sd2 = sd\nH0: m2 = m1  versus  Ha: m2 != m1; m2 > m1\n\nStudy parameters:\n\n        alpha =    0.0500\n        power =    0.8000\n            N =     1,000\n  N per group =       500\n           m1 =    0.0000\n           sd =    1.0000\n\nEstimated effect size and experimental-group mean:\n\n        delta =    0.1774\n           m2 =    0.1774\n```\n:::\n:::\n\n\nThis calculates the minimum effect size you can detect with the given sample size.\n\n**Stata code:**\n\nAs shown in the graph, with 500, 750, 1,000, 1,250, and 1,500 students, researchers can detect smaller treatment effects as the sample size increases.\n\n::: {#1ab00aa6 .cell execution_count=6}\n``` {.python .cell-code}\n%%stata\npower twomeans 0 , n(500(250)1500) power(0.8) sd(1) graph\n```\n\n::: {.cell-output .cell-output-display}\n![](how-to-power-calculation_files/figure-html/cell-7-output-1.svg){}\n:::\n:::\n\n\nAdditional exercises are available in the following do file: [Download power.do](/assets/files/sample-size-power.do)\n:::\n\n::: {.callout-tip collapse=\"true\"}\n\n## 🧮 Case 3: Estimate Power for a Given Sample Size and Effect\n\n**Goal:** Determine the statistical power based on your sample size and expected effect.\n\n**Assumptions:**\n\n- Study sample size: 1,000\n- Effect size: 0.2 S.D.\n- Variance of the outcome variable: 1 S.D.\n\n**Stata code:**\n\n::: {#65825369 .cell execution_count=7}\n``` {.python .cell-code}\n%%stata\npower twomeans 0 0.2 , n(1000) sd(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nEstimated power for a two-sample means test\nt test assuming sd1 = sd2 = sd\nH0: m2 = m1  versus  Ha: m2 != m1\n\nStudy parameters:\n\n        alpha =    0.0500\n            N =     1,000\n  N per group =       500\n        delta =    0.2000\n           m1 =    0.0000\n           m2 =    0.2000\n           sd =    1.0000\n\nEstimated power:\n\n        power =    0.8848\n```\n:::\n:::\n\n\nThe estimated power under these assumptions is 0.8,848.\n\n**Stata code:**\n\nSmaller samples lead to less power. As sample size increases, studies reach a larger probability of avoiding a type II error or false negative.\nIn the graph, as the sample size increases, the estimated power also increases. This means studies are more likely to detect a true effect with a larger sample.\n\n::: {#f03c582b .cell execution_count=8}\n``` {.python .cell-code}\n%%stata\npower twomeans 0 0.2 , n(100(100)1000) sd(1) graph\n```\n\n::: {.cell-output .cell-output-display}\n![](how-to-power-calculation_files/figure-html/cell-9-output-1.svg){}\n:::\n:::\n\n\nAdditional exercises are available in the following do file: [Download power.do](/assets/files/sample-size-power.do)\n:::\n\n## Additional Resources\n\n- [Stata Power and Sample Size Manual](https://www.stata.com/manuals/power.pdf)\n- [Optimal Design Software](https://www.wtgrantfoundation.org/optimal-design-software): Free tool for complex designs\n- [G*Power](https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower.html): User-friendly power calculator\n- [J-PAL's Power Calculations Guide](https://www.povertyactionlab.org/resource/power-calculations)\n\n",
    "supporting": [
      "how-to-power-calculation_files"
    ],
    "filters": [],
    "includes": {}
  }
}