---
title: "The IRB Lifecycle"
abstract: "The typical IRB lifecycle consists of multiple stages including the initial application, amendments, renewals, reporting unexpected events, and closure."
date: last-modified
authors-ipa:
  - "[Alexandra Krstić](https://poverty-action.org/people/alexandra-krstic)"
  - "[Daniela Carrillo](https://poverty-action.org/people/daniela-carrillo)"
keywords:
  - "institutional review board"
  - "research ethics"
  - "human subjects research"
  - "research approval"
  - "reference"
license: "CC BY"
---

:::{.callout-tip appearance="simple"}
## Key Takeaways
* IRB project oversight begins with initial approval before study implementation and continues through required amendments, periodic renewals, and reporting of unexpected events.
* Oversight ends only when all human subjects interactions and PII data analysis are complete, requiring a formal closure submission.
:::

## Initial Application
The IRB project lifecycle starts with the [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_original_application_form_updated_2020) of the initial application. Research teams submit an initial application to formally apply for **IRB review and must secure approval before implementing a new research study**. During this process, the IRB determines the review level -- expedited or full board -- and frequency of continuing review—one or three years.

The submission should include the following documents:

- [IPA IRB Initial Application Form](https://poverty-action.org/sites/default/files/IPA-IRB-Original-Application_March-2022-Updated.docx)—once approved, this becomes the study's protocol
- Instruments (e.g., surveys, interview/focus group discussion guides, observation forms)
- Informed consent forms, the [IPA IRB consent checklist and template](https://poverty-action.org/sites/default/files/2023-09/IPA-IRB-Consent-Form-Checklist-and-Template-Formatted.pdf) helps ensure all required and assessed elements are included
- Human Subjects Certificates for all Principal Investigators (PIs) and research personnel. Human Subjects training certification must be renewed every three years to remain valid for approval
- IRB approval from local IRBs and/or other institutions
- Data Sharing Agreements
- Any other supporting documents

IPA IRB evaluates submissions on a rolling basis in the order they receive them. Upon receipt of an IRB submission for review, the IRB evaluates the research study to determine whether it involves no more than minimal risk to the subjects.

Minimal risk means that the probability and magnitude of harm or discomfort anticipated in the research are not greater than those ordinarily encountered in daily life or routine procedures.

You can expect to receive feedback on your submission's risk assessment within 10 business days of your initial submission. If the submission is incomplete or requires further clarification/modification, the approval timeline will depend on the nature of the necessary changes and the responsiveness of the responsible research staff.

**If the IRB determines your project is minimal risk, it will undergo an expedited review**. In expedited review, an IPA IRB representative designated by the IPA IRB Chair conducts the review rather than the full board. The IRB conducts these reviews on an ongoing basis.

This means the research team does not need to wait for the next full board meeting for review or approval. Practically speaking, this means that the review usually takes less time than a non-minimal risk study.

Research teams cannot request expedited review, as this reflects the study's risk level, which only the designated representative of IPA IRB can determine.

**If a project is non-minimal risk, the IRB Coordinator or the chair will refer the study to the full IRB Board**. The Board will review the study at the monthly meeting and then either propose changes or grant a decision.

If you think your project may be non-minimal risk, you must submit the complete materials for the study by the deadline associated with the corresponding targeted meeting date. If your submission is missing documents at the deadline, the IRB may not consider it for that meeting date.

Non-minimal risk applications that may need full board review should allow for 60 days to process. The convened board may have questions or comments for the research staff that need re-discussion at the next meeting before approval.

Please note that if your pilot activity is collecting identifiable data that will be used during the study, you must budget enough time for the IRB to approve your application before starting your pilot activities.

## Amendments

Amendments are modifications to the previously approved study protocol or documents. Research teams should have **IRB review and approval of these modifications before implementation** to ensure that the regulatory criteria for IRB approval are met and that the risk/benefit ratio remains reasonable. Research teams must submit amendments through [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_amendment_form_updated_2020) and should include the following documents:

- [IPA IRB Amendment Form](https://poverty-action.org/sites/default/files/02-IPA-IRB-Amendment-Form.docx)
- Updated protocol
- Updated instruments, if proposing changes
- Updated informed consent forms, if proposing changes
- Updated Human Subjects Certificates, if expired or proposing changes to PIs and/or research personnel
- Any other supporting documents

Like application submissions, the IRB does not review all amendment submissions at a full board meeting; only non-minimal risk submissions require full board review. As long as your modification does not increase the risk of the research, the IRB will review it under expedited procedures. Regardless, you should submit your amendment as early as possible.

Note that if you are also due for a renewal, you can submit for changes and for the renewal -- which extends the approval by one year or three years -- with just the renewal form. More information on renewals can be found below.

## Renewals

Renewals allow the IRB to provide continuing oversight of a research study by reviewing its progress and determining whether it continues to meet the regulatory criteria for approval. The IRB determines the renewal frequency in the initial application review. You can find this information in the approval letter, and it depends on risk level, funding and start date.

**The renewal frequency is every three years for studies that meet the following requirements**:

- Are minimal risk
- Are not federally funded
- Don't include vulnerable populations
- Don't include sensitive questions
- Started after October 2022

**All other studies should be renewed annually.**

Research teams must submit renewals through [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_renewal_closure_form_updated_2020) and should include the following documents:

- [IPA IRB Renewal Form](https://poverty-action.org/sites/default/files/IPA-IRB-Renewal-Form-Revised-Aug-2022.docx)
- Updated protocol (if also proposing changes)
- Updated instruments, if also proposing changes
- Updated informed consent forms, if also proposing changes
- Updated Human Subjects Certificates, if expired or proposing changes to PIs and/or research personnel
- Any other supporting documents

::: {.callout-warning}
## Avoid delays or other issues by following IRB dates
Research teams should submit renewals well in advance of the expiration date to avoid lapses in IRB approval. If a study's approval expires, all research activities involving human subjects—data collection, contact with subjects, analysis of personally identifiable data (PII)—must stop until the IRB grants renewal.

In the progress report, you must also list the project's progress since last review, indicate why you missed the deadline, what human subjects research activities have taken place during the lapsed time, if any, and what steps the PI will take to avoid missing deadlines in the future.

Depending on the circumstances and length of delay in a continuing review, you may also need to submit an unexpected event report, as this may represent serious or continuing non-compliance with reporting implications. If the renewal includes modifications, the IRB should **review and approve these proposed changes before implementation**.
:::

Note that renewal submissions are due each year or every three years, as applicable, at the time that the IRB approved the Initial Application, not a year or three years after the most recent Amendment approval.

## Unexpected Events

Unexpected events are events that are not listed as risks in the protocol and/or informed consent forms like deviations or adverse events that result in harm to subjects. Research teams must **report them to the IRB** through [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_renewal_closure_form_updated_2020) **within five calendar days** and should include the following documents:

- [IPA IRB Unexpected Event Form](https://poverty-action.org/sites/default/files/03-IPA-IRB-Unexpected-Event-Form.docx)
- Updated protocol, if needed
- Any other supporting documents

If you miss the deadline for reporting an unexpected event, it is still in the best interest of your project to report the event regardless of when it occurred. IPA is committed to protection of human subjects and will work with all Country Programs to ensure appropriate protections occur and that research teams take appropriate responses when an unexpected event happens.

::: {.callout-tip}
After submission, the IRB may require a corrective action plan to address the problem and, depending on the findings, may require additional reporting, for example, to the donor.
:::

## Closure

A closure submission notifies the IRB the study is complete and ends the study team's obligation to provide updates, resulting in the end of the IRB oversight. Research teams must submit closures through [online submission](https://innovationsforpovertyaction.formstack.com/forms/irb_renewal_closure_form_updated_2020) and should include the following documents:

- [IPA IRB Closure Form](https://poverty-action.org/sites/default/files/IPA-IRB-Closure-Form-Revised-Aug-2022.docx)
- Any other supporting documents

Research teams can close studies when data collection or interaction with subjects is complete and data analysis with PII is complete.

Please note also that IPA IRB does not maintain a PII destruction policy and advises the following instead:

- Research teams may never publish identified data in a public repository without respondent consent. Please verify that your dataset does not contain any identifiers before publishing.
- Keeping identified information on file increases the risk of a confidentiality breach. IPA IRB encourages investigators to weigh and re-assess this risk against the benefit of keeping this information, considering their project's unique circumstances and content.
- If the research team keeps identifiable information on file, they must keep this information confidential. IPA IRB assumes that the data security protections for the project PII will remain the same after the study's closure, unless the research team has notified them of other arrangements. IPA IRB retains the right to disallow alternative data security and confidentiality procedures for specific projects on a case-by-case basis.
- If the research team intends to contact subjects past the closure of the study for any reason, the original informed consent must have allowed for the possibility of re-contact for the express purpose proposed by the researchers. The reviewing IRB for the closed study—and, if applicable, the IRB reviewing any new study—must also approve re-contact before the research team may implement it.
