---
title: "Survey Planning"

#------------------------------------------------------------------
# Authors
#------------------------------------------------------------------
# Authors are the main creators of the site's content, credited
# for their work and responsible for its core development,
# including writing and editing.
#------------------------------------------------------------------
authors-ipa:
    - "[David Torres](https://poverty-action.org/people/david-francisco-torres-leon)"
#------------------------------------------------------------------
# Contributors
#------------------------------------------------------------------
# Contributors provide support, such as feedback or supplementary
# materials for the site. They can also be responsible for
# updating/maintaining the site.
#------------------------------------------------------------------
contributors:
    - "[Cristhian Pulido](https://poverty-action.org/people/cristhian-pulido)"
    - "[Ishmail Azindoo Baako](https://poverty-action.org/people/ishmail-azindoo-baako)"
---

:::{.custom-summary-block}
The survey plan is an operational plan that covers timelines, staffing needs, logistics, and procurement for your data collection efforts.
:::

:::{.callout-tip appearance="simple"}
## Key Takeaways
* A survey plan is a document that outlines the steps and considerations necessary for conducting a survey, including questionnaire development, manpower requirements, timeline for data collection, logistics, survey tracking, respondent tracking, storage, training surveyors, equipment needs, and financial planning.
* The survey plan serves as a guide to ensure that all aspects of the survey are well-organized and executed efficiently.
:::

## Developing a Survey Plan
A survey plan needs to be written as you design your questionnaire and make decisions on whether it should be an electronic or paper survey. You will need to share your survey plan with others working with you like the Country Director, PI’s, country level and HQ survey support staff. For paper surveys, as early as possible give a heads up to the in-house data entry staff, if you have a data entry unit in your country or a data entry company so you can make sure your timeline fits their schedule and you can get the data as quickly as possible after fieldwork finishes. The same applies for dedicated programming staff if your survey is digital. Your survey plan can work as a running document where you fill details as you figure them out. It should include the following:

- **Questionnaire Development**: piloting questionnaires, translation, back translation, who will be involved at these stages, where will you pilot the survey - keep in mind not to go to actual survey respondents but find people similar – and how will you analyze the data.
- **Manpower**: who do you need to hire for surveying and quality control and what are the payment structures for staff. When will you hire people -- think about the structure and composition you want for your team. You might want to hire some senior people to help you with piloting the questionnaire and hiring other surveyors who will serve as team leaders/field managers when you start actual surveying. You might decide to go with a survey company. If you do, consider what they will take care of and what you will. Read the guide to deciding between a survey company and hiring your own team, and the quality control guide.
- **Timeline for data collection**: when will piloting the questionnaire happen, when will training happen, when will surveying start and finish. Read the section on timeline below.
- **Logistics**: how will you move teams across survey regions, transportation, accommodation, food etc. If you’re surveying electronically, how you will charge, store and secure your devices. Read the section on logistics below.
- **Survey Tracking**: how will you stay on top of the progress made in surveying, how many surveys should be completed per day, monitor data collection and keep track of which surveys are being checked.
- **Respondent tracking**: what information do you want to collect, who tracks hard to find respondents, how much time do you devote, how do you decide when to drop a respondent, what’s your replacement plan. Read the guideline on tracking respondents.
- **Storage**: where will surveys or electronic devices be stored – Do you need a field office?
- **Training Surveyors**: where will training happen, how long will it go on for, what should be on the training agenda, how will you incorporate as much field training as possible, how many surveyors do you want to recruit. Read the materials on training surveyors and creating a survey manual.
- **What equipment and other items do you need to buy**: gifts for respondents, any equipment for taking anthropometric measurements, other survey material (e.g., stationery) for surveyors. Read the section on survey materials below.
- **Your time**: You are responsible for the whole survey and there are a number of things happening simultaneously that require your attention. It might be a good idea to designate time for things- e.g., Friday look at back check data, Monday go out to the field -- so that you don’t forget anything during data collection.

### Timeline
While estimating when the survey will be complete is an inexact art, it is essential to do it well because data is often time-sensitive and must be collected while a program is running. Data collection must occur within a specific period to be comparable to others in the same survey or your budget restricts you to a long or short survey period. That means you need to plan realistically what your team can accomplish, learn immediately if you are falling behind your timeline and adapt quickly with a revised plan.

Specific plans vary according to the programs being evaluated, the survey, team structures, and geography. The core of your plan is deciding how many surveys you expect each person to complete each day. The following are some general principles that should guide this calculation:

- **Traveling to Respondents**: You need to develop a good sense of how long it’ll take to find a specific respondent. This may vary across the regions, districts or neighborhoods in your sample. Before fielding the survey, figure out which areas will be the most difficult to find respondents and which will be relatively easier. Consult maps with roads and anyone with local knowledge, from local partners to shop owners. Also, think about how long it’ll take surveyors to get to the survey area from their accommodation and include this in your calculation of the working day. It’s tempting to not include travel time in your work day, but you do this at your own peril. Travel time is one of the most common factors that delay a survey.
- **Finding Hard to Find Respondents**: Finding all respondents in a cluster often requires several attempts and needs to be factored into your expectations of how many surveys your team will perform each day. Identify what is the best time to find respondents in your survey sample- e.g., if it’s a period of heavy agricultural activity most people may be at their farms for some duration of the day and try to find out what time this might be. Finding respondents in the follow-up/endline survey will take more time than the baseline as some respondents may have moved and your team will need to sleuth out additional information to find them. Read the guide on Respondent Tracking.
- **Survey Time**: From the piloting of the questionnaire, you should have a sense of how long it takes to complete a single questionnaire. Based on this estimate as well as travel and tracking time, set a target number of surveys to be completed per day by each surveyor. Keep in mind that during the initial days of the survey, most surveyors will not reach their target. However, it is advisable that this only be factored into your timeline and average daily return calculations, but not into the daily target you set for your team. Surveyors should be given target estimates based on what is expected to be completed per day after the initial slowness of data collection is over.
- **Holidays**: Be sure to factor in national and local holidays. Consult with partner staff about which holidays they follow and could affect respondent availability. Some locations have so many holidays it may seem impossible to work!
- **Treatment/Control Balance**: Finally, be sure that treatment and control respondents/areas are surveyed in a balanced manner. Don’t survey all the controls and then all the treatment, but rather try to survey them simultaneously and as evenly as possible over the survey period.

### Logistics
As a field RA, your job is to make sure everything happens when it is supposed to, which means you need to be a mean multitasker and be able to inspire the best out of your survey team. Delegating the logistics in large surveys to a survey company or in-country management teams reduces some of the management burden, but you will still need to verify proper planning and timely execution. If surveying is considered a low paying, low skilled job in your area it might not attract people who take the initiative to recognize whether they have everything they need to do their job. Think about building in accountability systems into your field plan to incentivize people to meet targets and tell you when they hit a roadblock in the field.

In general, when planning the movement of teams, start with easy places to survey. Surveyors generally take more time in the early days to reach their target number of respondents and working in villages that are close by or where you’ll be able to find respondents easily reduces stress on you and your team. If the survey launches in several regions of the country simultaneously, consider a phased start of surveying so you can spend time with each team as they launch to be able to put out fires and improve practices before the whole team starts surveying.

Here are some things to consider when planning logistics:

- **Transportation Methods**: How will the teams travel to villages and sometimes even within villages? Will you give them a travel allowance and they organize their own transportation or will you need to organize a communal method? If you’re organizing, how many teams can fit in a minivan? Does every team need their own vehicle?
- **Directions to survey locations**: Maps may not always give you the most accurate directions to a village. How will you find villages? How will you make sure that it is the right village? Who is responsible for making sure the team is in the right location?
- **Accommodation**: Where will teams stay? Will they find their own accommodation or will you need to organize? Are there convenient accommodation options close to the villages you survey? If not, should you think about teams staying in villages? In this case, arrangements (mattresses, cooking equipment) will need to be organized. It is advisable for teams to stay together when they need to stay outside their home base. This allows you to make sure everyone arrives on time and coordinate evening meetings when the team comes back. If they make their own accommodation arrangements, consider imposing penalties for late arrivals because it slows down the whole team.
- **Food**: Where will people have their lunch? How long are they allowed to break on the field? Are there options in the village or will they need to travel far to find food? Encourage teams to pack their own food if this is the case.
- **Communicating with Local Authorities**: You may need to get permission to survey from district officials. Print letters that can be given to officials- decide who will go meet them.
- **Finding the right respondent**: How will the surveyors a) find the respondent and b) make sure it’s the right respondent? One option is to send mobilizers (well-informed and trusted community members or leaders) before the survey team to find respondents and slot interview appointments so that the surveyors don’t waste time finding respondents.
- **Equipment**: how are you printing all survey materials? How will you distribute them to staff? For phone surveys, how are you distributing SIM cards? How are you managing the sign-in and sign-out of devices/tablets/phones? Is there any other equipment that enumerators need to complete surveys?
- **Productivity**: How many surveys should each enumerator strive to complete per day? How will they know which respondents to attempt on each working day?
- **Internet access**: For digital data collection in particular, you should consider what speed of internet is available and how reliable it is. You also need to think about whether the internet is sufficient for uploading the types of files that you have. For example, audio files require much more bandwidth than survey data. For remote areas, consider setting up a local area network at your field office, to enable analysis of collected data without connecting to the internet. SurveyCTO offline sync simplifies this process. Be sure that you have a plan for sending airtime to enumerators to conduct and send in surveys once they are completed. If you are offering airtime as a respondent gift, you should set up the system for sending to specific phone numbers.

## Financial Plan
Managing your finances is one of the biggest, hidden headaches of keeping your field team moving. How you’re going to get money to the team, when they will be paid and how much should definitely be part of your field plan. Here are a few things to consider when creating your financial plan:

- **Payment Lag**: Keep in mind that there is often a lag between when surveyors start work and they get paid. If you are paying surveyors per diems and transport allowance, this can be a problem if they are required to buy their own transportation fuel or food upfront. Consider providing these until they are paid, giving a start of project bonus or loan (which can be automatically deducted from their first payment). Failing to plan for this can slow the launch of a survey.
- **Paying in Cash vs. Direct Deposit**: Definitely discuss this decision with your in-country management team. In countries where you can deposit funds into bank accounts, remember that it can take a significant amount of time to withdraw money from a bank. If you’re paying per diems this way, it can lead to field delays and needs to be accounted for in your timeline. While cash may be easier to make happen logistically and result in few delays, it is also a major security risk. Make sure you have procedures in place to get the money safely from the bank and then hold your team accountable so you can de-incentivize them from embezzling funds and catch any money problems early.
- **Sending Airtime/Internet to Enumerators and Respondents**: Create a system for sending internet to respondents if you are offering airtime as a respondent gift. Ideally, you should have someone in your office or give enumerators the ability to send airtime directly to a phone number. Enumerators must have enough internet to send in surveys or airtime to conduct surveys if they are conducting phone surveys.

## Survey Materials
Make field departure and return checklists of things people need to do before they go out into the field and close for the day. Consider pasting these procedures to your office on the door so people can check if they have everything they need before they head out.

The field leadership team, i.e. Team Leader, Field Managers, is responsible for making sure this is followed. You may want to consider creating tracking forms, sign in/out sheets to help hold them and the team accountable. This is especially important in electronic surveying as you want to be sure that equipment like phones, PDAs, and netbooks are well-taken care of and you can hold the right person accountable if one is lost.

### Equipment
Many projects need to purchase equipment for the field office or to collect anthropomorphic measures such as height, weight, or health indicators. Many institutions require getting price quotes from three or more vendors, which is a good practice, and will help you develop your negotiating skills. You should take an inventory of your office equipment, including the condition, at the beginning and end of the survey period to make sure nothing is lost or damaged.

For all equipment going to the field, it is highly recommended to put serial numbers on each piece and have surveyors check them out and check them in regularly for inspection. These machines are often subjected to rough conditions, and depreciate quickly. One way to improve your data is to have surveyors record the serial number of the machine used for each survey. That will help you identify systematic errors in machines.

### GPS Units
Some surveys use GPS units to record GPS readings to aid in locating and verifying the right household in subsequent surveys. Often team leaders or people doing the census exercise are responsible for taking GPS readings to minimize the number of units required. Make sure you send them with additional batteries and budget for a few more GPS units than the people taking GPS readings to allow for units breaking on the field. Be sure to set the same coordinate format on all units before sending them to the field so you don’t have to convert them later.

One point to note about GPS readings is that they are helpful in finding respondents in subsequent surveys but may not be sufficient. Unless you have GPS units that are accurate to within 5 meters there is bound to be some confusion in subsequent surveys. Traditional tracking methods – such as hand-drawn maps, collecting phone numbers and contacts – should be used to complement the GPS readings and provide a secondary method to find respondents. These methods should not be abandoned simply because GPS readings are taken.

## Tablets and phones
IPA recommends buying devices from trusted brands such as Samsung or Google. It is important to buy sturdy cases to avoid breaking your devices. Many projects will find that extra battery packs are a necessity in the field. You should do field piloting of your devices to work out the kinks early on so you can budget for the necessary equipment when making your survey plan. You should also consider buying a gasoline or diesel generator if power is unreliable.

If you are conducting a phone survey, be sure that enumerators also have headphones, battery packs, and charger cables. If you are asking enumerators to use their own phones, SIM cards should be provided so enumerators are not using their own phone numbers.

### Equipment for surveyors
You will need to make sure that your team has all the basic equipment it needs for the field. This includes:
- **Bags and Folders**: for surveyors to organize their questionnaire. Consider getting something durable and rain proof to protect equipment and/or questionnaires.
- **Umbrellas/Rain Coats**: If you’re asking your team to work through rainy season, this can help them persevere through a drizzle.
- **Stationery Items**: include pencils, sharpeners and erasers and, potentially, a stapler per team.
- **ID cards for surveyors**: This helps surveyors establish credibility when surveying. T-shirts and hats with the IPA logo can also help.

### Respondent gifts/ incentives

#### Choosing gifts
Often surveys give the respondent gifts or incentives to compensate them for their time. Some surveys have given money but it is recommended that it be used rarely and preferably only when you’re taking someone’s time when they would otherwise be working. Sometimes the money for respondent gifts is used to play games eliciting risk aversion, however, this runs the risk of some respondents feeling under-compensated and moreover surveyors might like to be nice to respondents and let them “win” coin tosses.

Generally, you do not want to choose a gift that is extremely valuable to the survey respondent. This can run into issues with ethics since it is important to avoid having undue influence when a respondent feels they have no choice but to be interviewed because of the incentive involved. Because of this, survey gifts must be approved by your IRB.

Some of the items that have been given by past IPA projects include sugar, cooking oil, washing soap bars, pencils, and sharpeners for school kids. Some projects have also given IPA T-shirts and IPA key chains but be careful with these. In a project in Ghana, farmers were given IPA T-shirts and some farmers wanted to form an association of IPA respondents in a village!

Items for the household are a safe bet because they’re useful no matter which respondent receives the gift. Some of these items could be bulky, making it a struggle to carry them on the field. You need to factor in how the team will carry these items on the field, since spillage or leaking may damage surveys or expensive equipment if they’re carried in the same bag. One common gift phone cards since are easy to cart around, and they facilitate phone back checks or tracking later on. With all gifts, and phone cards in particular, the challenge is to set up a system to verify that respondents received their gifts and they were not taken by the surveyors. Consider including a question in your back check survey about receiving the gift or a shorter phone follow up.

#### Treatment v. Control Gifts
If you’re working on a project where a loan or capital is given as one of the treatments, you may want to consider a) how you present the cash to the respondents and b) a nice gift for the control group as well to maintain good relations. It can be hard to maintain a good relationship with control respondents when they hear that others participating in the study received 100GHC and they didn’t. No matter how many times you explain it’s random, like winning the lottery, you will still have some disgruntled respondents. Projects have given control groups nicer gifts from flashlights to nice sets of stationery to compensate for the disappointment of not receiving a big prize.
Another thing to consider is how the gift is presented. You may want to allow respondents to rip open an envelope or scratch off a scratch card to heighten the feeling of winning a prize, rather than simply being given a gift for their time.

*Last updated February 2025.*
