---
title: "Visual Studio Code"
abstract: >-
  "Visual Studio Code (VS Code) is a versatile code editor used for writing, editing, and developing text-based documents and programs. It is recommended for collaborative code-first data and technology projects at IPA."

# Authors
# Authors are the main creators of the site's content, credited for their work and responsible for its core development, including writing and editing.
authors-ipa:
  - "[Niall Keleher](https://poverty-action.org/people/niall-keleher)"

  # Contributors
  # Contributors provide support, such as feedback or supplementary materials for the site. They can also be responsible for updating/maintaining the site.
  # contributors:
  #   - "[Contributor 1](https://poverty-action.org/people/contributor1_name)"

license:
  text: "CC BY-SA"
  url: https://creativecommons.org/licenses/by-sa/4.0/

format:
  html: default
  # typst: default
categories:
  - explanation
---

## How to Install VS Code?

To install VS Code, download and install the latest software version from the
Visual Studio Code [website](https://code.visualstudio.com/) or run the
following from the command line if you have the Windows Package Manager,
`winget`, installed:

::: {.panel-tabset group="OS"}
# Windows

```bash
winget install Microsoft.VisualStudioCode
```

# MacOS

```bash
brew install --cask visual-studio-code
```

# Linux

```bash
sudo snap install code --classic
```
:::

## Using VS Code

The best starting point for familiarizing yourself with VS Code is the
[documentation](https://code.visualstudio.com/docs).

Some particularly helpful references in the documentation are:

- [Editing with VS Code](https://code.visualstudio.com/docs/editor/codebasics)
- [Git Source control in VS
  Code](https://code.visualstudio.com/docs/sourcecontrol/overview)
- [Python in VS
  Code](https://code.visualstudio.com/docs/python/python-quick-start)

## Recommended Extensions

The core software and functionality in VS Code gives you a lot of useful tools
for writing, editing, and collaborating. Additionally, you can add functionality
through
[Extensions](https://code.visualstudio.com/docs/editor/extension-marketplace).

Some helpful extensions are the following:

- [Python
  Extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python)
  \- language syntax for Python programming
- [Ruff](https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff) -
  Python linting and code formatting
- [R
  Extension](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r) -
  Interacting with R from VS Code
- [GitHub Pull
  Requests](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github)
  \- review and manage GitHub pull requests and issues in Visual Studio Code
- [Jupyter
  Extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)
  \- for developing with jupyter notebooks
- [Just](https://marketplace.visualstudio.com/items?itemName=nefrob.vscode-just-syntax)
  \- support for Justfiles
- [Quarto
  Extension](https://marketplace.visualstudio.com/items?itemName=quarto.quarto)
  \- support for writing and building Quarto projects
- [Markdown All in
  One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)
  \- support for Markdown
- [Markdown Preview Mermaid
  Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)
  \- support for [Mermaid](https://mermaid.js.org/intro/) diagrams in Markdown
- [Conventional
  Commits](https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits)
  \- support for writing easy to understand commit messages
