---
title: "Virtual Environments"
# Authors
# Authors are the main creators of the site's content, credited for their work and responsible for its core development, including writing and editing.
authors-ipa:
  - "[Niall Keleher](https://poverty-action.org/people/niall-keleher)"

# Contributors
# Contributors provide support, such as feedback or supplementary materials for the site. They can also be responsible for updating/maintaining the site.
# contributors:
#   - "[Contributor 1](https://poverty-action.org/people/contributor1_name)"
---

:::{.custom-summary-block}
The use of virtual environments is recommended when working on shared projects. Virtual environments create an isolated workspace for each project, helping to prevent conflicts between dependencies that may require different versions of the same package.
:::

## Python Virtual Environments

We recommend using `uv` to manage Python virtual environments as it provides an
overarching framework for managing Python installations and virtual environments. See
information on `uv` in the [uv documentation](https://docs.astral.sh/uv).

## R Virtual Environments

R virtual environments can be created using the `renv` package. See
[documentation](https://rstudio.github.io/renv/articles/renv.html) for more information
about how to use `renv`.

## Docker

[Docker](https://docs.docker.com/get-started/overview/) is a tool that allows you to
create, deploy, and run applications using containers. In some instances, it may be more
appropriate to use Docker containers to manage your project environment, especially when
there is a project environment that needs to be deployed to cloud computing services.

## Learning Resources

- [A Complete Guide to Python Virtual Environments](https://www.dataquest.io/blog/a-complete-guide-to-python-virtual-environments/)
- [Real Python, Python Virtual Environments](https://realpython.com/python-virtual-environments-a-primer/)
- [Python Virtual Environments](https://docs.python.org/3/tutorial/venv.html)
- [R Virtual Environments](https://rstudio.github.io/renv/articles/renv.html)
