---
title: "IPA's Data Management System"

#------------------------------------------------------------------
# Authors
#------------------------------------------------------------------
# Authors are the main creators of the site's content, credited
# for their work and responsible for its core development,
# including writing and editing.
#------------------------------------------------------------------
authors-ipa:
  - "[Ishmail Baako](https://poverty-action.org/people/ishmail-azindoo-baako)"
  - "[Lindsey Shaughnessy](Lindsey Shaughnessy)"
#------------------------------------------------------------------
# Contributors
#------------------------------------------------------------------
# Contributors provide support, such as feedback or supplementary
# materials for the site. They can also be responsible for
# updating/maintaining the site.
#------------------------------------------------------------------
contributors:
  - "[Contributor 1](https://poverty-action.org/people)"
  - "[Contributor 2](https://poverty-action.org/people)"
---

> IPA's Data Management System (DMS) is a package of Stata-and-Excel-based tools that automates and assists with your project's data flow.

## What is the DMS?
IPA's Data Management System (DMS) is a Stata package that automates and assists with your project's data flow. The DMS assists you with the following functionality:

* **Creating folders and do-files:** Automatically creates a folder structure, Stata files and documentation, including for projects with multiple surveys (e.g. creates standardized folder structure, input files, do-files and readme files)
* **Deciding which quality checks are important to your project:** A simple global do-file with a detailed description of the different check features as well as a section to turn on and off specific checks based on your own needs (e.g. backchecks, field comments, survey tracking, duplicates, missing values, outliers, text audits etc)
* **De-duplicating:** Automatically flags all duplicates, and provides a summary of the differences of each duplicate group. Also, saves a new de-duplicated clean dataset so high-frequency checks can run.
* **Checking and reporting on data quality:** Runs high-frequency checks to flag issues with data quality (e.g. asks you to identify important checks and variables in the global do-file and Excel-based inputs sheets and automatically generates reports for interpretation and follow-up actions to improve data quality)
* **Checking and reporting on inconsistencies in the dataset:** Compares and reports on the differences in responses in the Survey & Backchecks datasets.
* **Corrections to the dataset:** Includes an easy-to-use excel-based tool for making and logging changes to data including replacements and values, dropping of observations and flagging HFC outliers values as correct.
* **Reporting on enumerator performance:** Generates enumerator reports with indicators of enumerator productivity and other general enumerator performance including Don't Know/Refuse/Missing/Other specify responses rate and summary statistics by specified variables.
* **Reporting on survey progress:** Generates progress reports on survey completion, by day/week/month and by a customizable filter variable (e.g. progress reports by region, district, village, treatment status)

## How to install the DMS?
To use the DMS, you will need Stata 17 or above. If you do not have Stata 17 or above, click on this knowledge article on Stata to learn how to request an upgrade from IPA's MIST team.

If you are installing the DMS for the first time, use this command in Stata:

```stata
net install ipacheck, all replace from("https://raw.githubusercontent.com/PovertyAction/high-frequency-checks/master"") replace
ipacheck update
```

To start your project's folder structure, use:

```stata
ipacheck new, surveys("NAME OF SURVEY") folder(“path/to/file/destination”)
```

Note that if you do not use the folder option, the folder structure will be created in your current working directory.
There is also an option to make subfolders for multiple surveys:

```stata
ipacheck new, surveys("Survey1" "Survey2") subfolders
```

## Learning to use the DMS
The DMS includes a practice exercise that can help you learn how to fill out the globals do-file and the input sheets of the DMS, work through the different output sheets, and make corrections. If you have already updated your ipacheck package using the code in the previous section, you can do the exercise on your computer using this code:

```stata
ipacheck new, exercise folder("path/to/file/destination")
```

Note that if you do not include the folder- option, the folders will be created in your current directory. This code will download the folder structure and input and replacement files as ipacheck new would, as well as:
* Practice survey data (in 4_data/2_survey folder)
* Sample data (in 4_data/2_survey)
* Backcheck data (in 4_data/3_backcheck)
* Text audit media files (in 4_data/2_survey/media)
* Comment media files (in 4_data/2_survey/media)
* Audio Audit files (in 4_data/2_survey/media)

If you already use an existing file structure, you can download the files only using:

```stata
ipacheck new, files folder(“path/to/file/destination”)
```

Please note that the folders and input structure of the DMS have changed in v4.0 so you will need to make some changes to the folder structure of do-files.

## When to implement DMS features into your project?

@tbl-1-dms describes some of the features that comprise the DMS, and when you should incorporate them based on the stage of your IPA project(s)

| Feature | Description | Before data collection | During data collection | After data collection |
|:-----------|:-------------------|:-------:|:-------:|:-------:|
| ipacheck new (Stata Command) | Creates a folder structure and/or input files for DMS. Also used to create DMS exercise |  X |  X   | |
| README files | Every folder has a readme file to list files, authors, changes, and anything necessary for a successful handover  |   123 |  123   | |
| DMS inputs file (Excel file) | Initializes inputs for outliers, other specify and enumerator stats checks.     |     1 |   1    | |

: Example DMS features by data collection stage Table {#tbl-1-dms}

::: {.callout-tip title="Do you have ideas for the DMS" collapse="false"}
Anyone can email requests for new features to researchsupport@poverty-action.org -- but we can't promise that we will immediately respond.
If you are a skilled coder, we would welcome contributions to our public GitHub repository. Again, email researchsupport@poverty-action.org to discuss a possible collaboration!
:::

::: {.callout-warning title="Do you need support with the DMS" collapse="false"}
If your research project has limited time or capacity to set up or run the DMS, the GRDS team is available at an hourly rate to provide direct technical support to any project. You can read more about these services (What is Direct Support?), or simply email researchsupport@poverty-action.org to discuss your options.
If you have configured your own DMS, and need troubleshooting support, please create a case for the GRDS team through the Global Help Desk. You can click the green button to your right that says "CONTACT SUPPORT", or click here.
:::
