name: formatting-and-writing-style
on:
  pull_request:
    branches:
      - main
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.12'
      - uses: pre-commit/action@v3.0.1
  vale:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: errata-ai/vale-action@2.1.2
        with:
          reporter: github-pr-check # Alternatives: github-pr-check, github-pr-review, github-check
          fail_on_error: false
          filter_mode: diff_context # Alternatives: added, diff_context, file, nofilter
          vale_flags: "--minAlertLevel=error"
          files: '["data-cleaning/", "data-collection/", "data-quality/", "data-security/", "research-design/", "research-ethics/", "software/", "index.qmd"]'
