name: Pre-commit
on:
  pull_request:
    branches:
      - disabled # enable to main when ready
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
