on:
  workflow_dispatch:
  push:
    branches: main
name: Publish Quarto Site
#docs: https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: ["3.12.3"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-python@v5
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: false
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PYTHON: ".venv/bin/python3"
